In [1]:
import os
import numpy as np
import pandas as pd
import tensorflow as tf
import warnings 
warnings.filterwarnings(action='ignore')


import tensorflow as tf
from sklearn.model_selection import train_test_split
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, GRU, Dropout, LSTM, InputLayer
from sklearn.ensemble import VotingClassifier, AdaBoostClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score
from sklearn import metrics 
from tensorflow import keras
import random  
from tensorflow.keras.callbacks import EarlyStopping

seed_num = 42
# os.environ["CUDA_VISIBLE_DEVICES"] = '-1'
gpus = tf.config.experimental.list_physical_devices('GPU')
print(gpus)
if gpus:
    try:
        for i in range(len(gpus)):
            tf.config.experimental.set_memory_growth(gpus[i], True)
    except RuntimeError as e:
        # 프로그램 시작시에 메모리 증가가 설정되어야만 합니다
        print(e)
gpus = tf.config.experimental.list_physical_devices('GPU')
seed_num = 42
random.seed(seed_num)

x = np.load('/project/LSH/x_(7727,10,4068).npy')
y = np.load('/project/LSH/y_(7727,1).npy')

idx = list(range(len(x)))
random.shuffle(idx)

i = round(x.shape[0]*0.8)
X_train, y_train = x[idx[:i],:,:], y[idx[:i]]
X_test, y_test = x[idx[i:],:,:], y[idx[i:]]

X_train.shape, y_train.shape, X_test.shape, y_test.shape


def get_model():
    lstm = Sequential()
    lstm.add(InputLayer(input_shape=(x.shape[1],x.shape[2])))
    lstm.add(LSTM(units=128, activation='hard_sigmoid', return_sequences=True))
    lstm.add(LSTM(units=64, activation='hard_sigmoid', return_sequences=True))
    lstm.add(Dropout(0.2))
    lstm.add(LSTM(units=64, activation='hard_sigmoid', return_sequences=True))
    lstm.add(LSTM(units=32, activation='hard_sigmoid', return_sequences=False))
    lstm.add(Dropout(0.2))
    lstm.add(Dense(units=1, activation='sigmoid'))

    lstm.compile(optimizer= keras.optimizers.Adam(learning_rate = 0.001), 
                 loss = "binary_crossentropy", metrics=['acc'])
    return lstm

from keras.wrappers.scikit_learn import KerasClassifier

class MyKerasClassifier(KerasClassifier):
    def fit(self, x, y, sample_weight=None, **kwargs):
        y = np.array(y)
        if len(y.shape) == 2 and y.shape[1] > 1:
            self.classes_ = np.arange(y.shape[1])
        elif (len(y.shape) == 2 and y.shape[1] == 1) or len(y.shape) == 1:
            self.classes_ = np.unique(y)
            y = np.searchsorted(self.classes_, y)
        else:
            raise ValueError('Invalid shape for y: ' + str(y.shape))
        self.n_classes_ = len(self.classes_)
        #---------------수정---------------
        if sample_weight is not None:
            print('sample weight : ', sample_weight)
            if sample_weight[0] == 0.00016175994823681658:
                print('x, y', x.shape, x.sum().sum())
                return super(MyKerasClassifier, self).fit(x, y, **kwargs)
            weights = sample_weight / sum(sample_weight)
            random_range = [(sum(weights[:i]), sum(weights[:i])+weights[i]) if i!=0 else (0, weights[i]) for i in range(len(weights))]
            random_nums = [random.random() for _ in range(len(weights))]
            idx_list = []
            for i in random_nums:
                for j in random_range:
                    if j[0] < i <= j[1]:
                        idx_list.append(random_range.index(j))
                        break
            new_x = x[idx_list, :, :]
            new_y = y[idx_list]
            print(new_x.sum().sum())
            print('new_x, new_y', new_x.shape, new_y.shape)
            return super(MyKerasClassifier, self).fit(new_x, new_y, **kwargs)
        
    def predict(self, x, **kwargs):
        return super(MyKerasClassifier, self).predict(x)

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU'), PhysicalDevice(name='/physical_device:GPU:1', device_type='GPU')]


Using TensorFlow backend.


In [2]:
import os
import numpy as np
import pandas as pd
import tensorflow as tf
import warnings 
warnings.filterwarnings(action='ignore')


import tensorflow as tf
from sklearn.model_selection import train_test_split
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, GRU, Dropout, LSTM, InputLayer
from sklearn.ensemble import VotingClassifier, AdaBoostClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score
from sklearn import metrics 
from tensorflow import keras
import random  
from tensorflow.keras.callbacks import EarlyStopping

seed_num = 42
# os.environ["CUDA_VISIBLE_DEVICES"] = '-1'
gpus = tf.config.experimental.list_physical_devices('GPU')
print(gpus)
if gpus:
    try:
        for i in range(len(gpus)):
            tf.config.experimental.set_memory_growth(gpus[i], True)
    except RuntimeError as e:
        # 프로그램 시작시에 메모리 증가가 설정되어야만 합니다
        print(e)
gpus = tf.config.experimental.list_physical_devices('GPU')
seed_num = 42
random.seed(seed_num)

x = np.load('/project/LSH/x_(7727,10,4068).npy')
y = np.load('/project/LSH/y_(7727,1).npy')

idx = list(range(len(x)))
random.shuffle(idx)

i = round(x.shape[0]*0.8)
X_train, y_train = x[idx[:i],:,:], y[idx[:i]]
X_test, y_test = x[idx[i:],:,:], y[idx[i:]]

X_train.shape, y_train.shape, X_test.shape, y_test.shape


def get_model():
    lstm = Sequential()
    lstm.add(InputLayer(input_shape=(x.shape[1],x.shape[2])))
    lstm.add(LSTM(units=128, activation='hard_sigmoid', return_sequences=True))
    lstm.add(LSTM(units=64, activation='hard_sigmoid', return_sequences=True))
    lstm.add(Dropout(0.2))
    lstm.add(LSTM(units=64, activation='hard_sigmoid', return_sequences=True))
    lstm.add(LSTM(units=32, activation='hard_sigmoid', return_sequences=False))
    lstm.add(Dropout(0.2))
    lstm.add(Dense(units=1, activation='sigmoid'))

    lstm.compile(optimizer= keras.optimizers.Adam(learning_rate = 0.001), 
                 loss = "binary_crossentropy", metrics=['acc'])
    return lstm

from keras.wrappers.scikit_learn import KerasClassifier
import random
class MyKerasClassifier(KerasClassifier):
    def fit(self, x, y, sample_weight=None, validation_split=0.25, **kwargs):
        y = np.array(y)
        if len(y.shape) == 2 and y.shape[1] > 1:
            self.classes_ = np.arange(y.shape[1])
        elif (len(y.shape) == 2 and y.shape[1] == 1) or len(y.shape) == 1:
            self.classes_ = np.unique(y)
            y = np.searchsorted(self.classes_, y)
        else:
            raise ValueError('Invalid shape for y: ' + str(y.shape))
        self.n_classes_ = len(self.classes_)
        #---------------수정---------------
        if sample_weight is not None:
            print('sample weight : ', sample_weight)
            if sample_weight[0] == 0.00016175994823681658:
                print('x, y', x.shape, x.sum().sum())
                return super(MyKerasClassifier, self).fit(x, y, **kwargs)
            print('x sum', x.sum().sum())
            
            idx = np.arange(len(x))
            random.shuffle(idx)
            i = int(len(x)*0.75)
            train_x, train_y = x[idx[:i],:,:], y[idx[:i]]
            val_x, val_y = x[idx[i:],:,:], y[idx[i:]]
            
            
            train_sw, val_sw = sample_weight[idx[:i]], sample_weight[idx[i:]]
            train_sw, val_sw = train_sw/sum(train_sw)*len(train_sw), val_sw/sum(val_sw)*len(val_sw)
            
            weights = val_sw / sum(val_sw)
            random_range = [(sum(weights[:i]), sum(weights[:i])+weights[i]) if i!=0 else (0, weights[i]) for i in range(len(weights))]
            random_nums = [random.random() for _ in range(len(weights))]
            idx_list = []
            for i in random_nums:
                for j in random_range:
                    if j[0] < i <= j[1]:
                        idx_list.append(random_range.index(j))
                        break
            new_val_x = val_x[idx_list, :, :]
            new_val_y = val_y[idx_list]
            
            kwargs['validation_data'] = (new_val_x, new_val_y)
            kwargs['sample_weight'] = train_sw
            return super(MyKerasClassifier, self).fit(train_x, train_y, **kwargs)
        
        return super(MyKerasClassifier, self).fit(x, y, **kwargs)
    
    
    
    def predict(self, x, **kwargs):
        return super(MyKerasClassifier, self).predict(x)

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU'), PhysicalDevice(name='/physical_device:GPU:1', device_type='GPU')]


# Adaboost-LSTM

## Single LSTM

In [36]:
X_train.shape

(6182, 10, 4068)

In [32]:
idx = np.arange(7727)
random.shuffle(idx)
idx

array([7267, 6914,  990, ..., 2575, 3450, 1696])

In [6]:
with tf.device('/device:GPU:0'):
    print("Single LSTM Start")
    model = get_model()
    
    early_stop = EarlyStopping(monitor='val_loss', patience=10, verbose=1, restore_best_weights=True)
    cb_checkpoint = ModelCheckpoint(filepath='./models/single_lstm.h5', monitor='val_loss',
                                    verbose=1, save_best_only=True)
    model.fit(X_train, y_train, epochs=50, batch_size=128, validation_split=0.25, callbacks=[early_stop, cb_checkpoint])
    preds = model.predict(X_test)

    preds[preds>0.5]=1
    preds[preds<=0.5]=0
    precision = precision_score(y_test, preds)
    recall = recall_score(y_test, preds)
    f1 = f1_score(y_test, preds)
    roc_auc = roc_auc_score(y_test, preds)
    acc = accuracy_score(y_test, preds)

    print(f'accuracy : {acc}, precision : {precision}, recall : {recall}, f1 : {f1}, roc_auc : {roc_auc}')

Single LSTM Start
Epoch 1/50
37/37 [==============================] - 6s 81ms/step - loss: 0.6736 - acc: 0.6055 - val_loss: 0.6657 - val_acc: 0.6177
Epoch 2/50
37/37 [==============================] - 3s 70ms/step - loss: 0.6696 - acc: 0.6100 - val_loss: 0.6509 - val_acc: 0.6177
Epoch 3/50
37/37 [==============================] - 3s 70ms/step - loss: 0.6045 - acc: 0.6706 - val_loss: 0.5288 - val_acc: 0.7510
Epoch 4/50
37/37 [==============================] - 3s 70ms/step - loss: 0.4900 - acc: 0.7821 - val_loss: 0.4942 - val_acc: 0.7639
Epoch 5/50
37/37 [==============================] - 3s 71ms/step - loss: 0.4187 - acc: 0.8261 - val_loss: 0.4894 - val_acc: 0.7743
Epoch 6/50
37/37 [==============================] - 3s 70ms/step - loss: 0.3760 - acc: 0.8503 - val_loss: 0.5036 - val_acc: 0.7743
Epoch 7/50
37/37 [==============================] - 3s 71ms/step - loss: 0.3591 - acc: 0.8613 - val_loss: 0.5329 - val_acc: 0.7587
Epoch 8/50
37/37 [==============================] - 3s 71ms/step 

In [11]:
%%time
from tensorflow.keras.callbacks import ModelCheckpoint

with tf.device('/device:GPU:0'):
    early_stop = EarlyStopping(monitor='val_loss', patience=50, verbose=1, restore_best_weights=True)
#     cb_checkpoint = ModelCheckpoint(filepath='./models/adaboost_lstm.h5', monitor='val_acc',
#                                     verbose=1, save_best_only=True)
    base_estimator = MyKerasClassifier(build_fn=get_model, epochs=300, batch_size=10000,
                                       validation_split=0.25, callbacks=[early_stop])
#     base_estimator = MyKerasClassifier(build_fn=get_model, epochs=50, batch_size=128, validation_split=0.25)

    boosted_classifier = AdaBoostClassifier(base_estimator=base_estimator, n_estimators=60, random_state=42, learning_rate=1.2)
    
    print("Adaboost LSTM Start")
    boosted_classifier.fit(X_train, y_train)
    preds = boosted_classifier.predict(X_test)

    precision = precision_score(y_test, preds)
    recall = recall_score(y_test, preds)
    f1 = f1_score(y_test, preds)
    roc_auc = roc_auc_score(y_test, preds)
    acc = accuracy_score(y_test, preds)

    print(f'Adaboost accuracy : {acc}, precision : {precision}, recall : {recall}, f1 : {f1}, roc_auc : {roc_auc}')

Adaboost LSTM Start
sample weight :  [0.00016176 0.00016176 0.00016176 ... 0.00016176 0.00016176 0.00016176]
x, y (6182, 10, 4068) 1644947.0
Epoch 1/70
2/2 [==============================] - 5s 538ms/step - loss: 0.6814 - acc: 0.6104 - val_loss: 0.6666 - val_acc: 0.6177
Epoch 2/70
2/2 [==============================] - 0s 134ms/step - loss: 0.6782 - acc: 0.6091 - val_loss: 0.6652 - val_acc: 0.6177
Epoch 3/70
2/2 [==============================] - 0s 141ms/step - loss: 0.6753 - acc: 0.6061 - val_loss: 0.6658 - val_acc: 0.6177
Epoch 4/70
2/2 [==============================] - 0s 135ms/step - loss: 0.6721 - acc: 0.6025 - val_loss: 0.6665 - val_acc: 0.6177
Epoch 5/70
2/2 [==============================] - 0s 135ms/step - loss: 0.6741 - acc: 0.6033 - val_loss: 0.6661 - val_acc: 0.6177
Epoch 6/70
2/2 [==============================] - 0s 133ms/step - loss: 0.6744 - acc: 0.6040 - val_loss: 0.6654 - val_acc: 0.6177
Epoch 7/70
2/2 [==============================] - 0s 136ms/step - loss: 0.6745 

2/2 [==============================] - 0s 135ms/step - loss: 0.3527 - acc: 0.8654 - val_loss: 0.5245 - val_acc: 0.7671
Epoch 58/70
2/2 [==============================] - 0s 126ms/step - loss: 0.3355 - acc: 0.8773 - val_loss: 0.5448 - val_acc: 0.7691
Epoch 59/70
2/2 [==============================] - 0s 137ms/step - loss: 0.3444 - acc: 0.8708 - val_loss: 0.5369 - val_acc: 0.7574
Epoch 60/70
2/2 [==============================] - 0s 136ms/step - loss: 0.3426 - acc: 0.8717 - val_loss: 0.5372 - val_acc: 0.7652
Epoch 61/70
2/2 [==============================] - 0s 125ms/step - loss: 0.3239 - acc: 0.8857 - val_loss: 0.5394 - val_acc: 0.7678
Epoch 62/70
2/2 [==============================] - 0s 134ms/step - loss: 0.3149 - acc: 0.8889 - val_loss: 0.5398 - val_acc: 0.7639
Epoch 63/70
2/2 [==============================] - 0s 136ms/step - loss: 0.3164 - acc: 0.8874 - val_loss: 0.5596 - val_acc: 0.7613
Epoch 64/70
2/2 [==============================] - 0s 128ms/step - loss: 0.3104 - acc: 0.8900 -

Epoch 44/70
1/1 [==============================] - 0s 172ms/step - loss: 0.6863 - acc: 0.3998 - val_loss: 0.6775 - val_acc: 0.3814
Epoch 45/70
1/1 [==============================] - 0s 177ms/step - loss: 0.6852 - acc: 0.3955 - val_loss: 0.6775 - val_acc: 0.3814
Epoch 46/70
1/1 [==============================] - 0s 189ms/step - loss: 0.6826 - acc: 0.3957 - val_loss: 0.6775 - val_acc: 0.3814
Epoch 47/70
1/1 [==============================] - 0s 177ms/step - loss: 0.6843 - acc: 0.3995 - val_loss: 0.6776 - val_acc: 0.3814
Epoch 48/70
1/1 [==============================] - 0s 188ms/step - loss: 0.6865 - acc: 0.3995 - val_loss: 0.6778 - val_acc: 0.3814
Epoch 49/70
1/1 [==============================] - 0s 180ms/step - loss: 0.6828 - acc: 0.3966 - val_loss: 0.6781 - val_acc: 0.3814
Epoch 50/70
1/1 [==============================] - 0s 186ms/step - loss: 0.6858 - acc: 0.3963 - val_loss: 0.6784 - val_acc: 0.3814
Epoch 51/70
1/1 [==============================] - 0s 183ms/step - loss: 0.6842 - a

1/1 [==============================] - 0s 179ms/step - loss: 0.6964 - acc: 0.5982 - val_loss: 0.6949 - val_acc: 0.5841
Epoch 31/70
1/1 [==============================] - 0s 156ms/step - loss: 0.6991 - acc: 0.5959 - val_loss: 0.6942 - val_acc: 0.5841
Epoch 32/70
1/1 [==============================] - 0s 151ms/step - loss: 0.6970 - acc: 0.5959 - val_loss: 0.6934 - val_acc: 0.5841
Epoch 33/70
1/1 [==============================] - 0s 156ms/step - loss: 0.6929 - acc: 0.5951 - val_loss: 0.6928 - val_acc: 0.5841
Epoch 34/70
1/1 [==============================] - 0s 169ms/step - loss: 0.6960 - acc: 0.5864 - val_loss: 0.6921 - val_acc: 0.5841
Epoch 35/70
1/1 [==============================] - 0s 184ms/step - loss: 0.7001 - acc: 0.5804 - val_loss: 0.6916 - val_acc: 0.5841
Epoch 36/70
1/1 [==============================] - 0s 179ms/step - loss: 0.6958 - acc: 0.5818 - val_loss: 0.6912 - val_acc: 0.5841
Epoch 37/70
1/1 [==============================] - 0s 143ms/step - loss: 0.6926 - acc: 0.5801 -

Epoch 17/70
1/1 [==============================] - 0s 183ms/step - loss: 0.7002 - acc: 0.5580 - val_loss: 0.6927 - val_acc: 0.6100
Epoch 18/70
1/1 [==============================] - 0s 180ms/step - loss: 0.7046 - acc: 0.5499 - val_loss: 0.6900 - val_acc: 0.6100
Epoch 19/70
1/1 [==============================] - 0s 183ms/step - loss: 0.6997 - acc: 0.5372 - val_loss: 0.6876 - val_acc: 0.6100
Epoch 20/70
1/1 [==============================] - 0s 180ms/step - loss: 0.7056 - acc: 0.5240 - val_loss: 0.6856 - val_acc: 0.6100
Epoch 21/70
1/1 [==============================] - 0s 176ms/step - loss: 0.6952 - acc: 0.5298 - val_loss: 0.6839 - val_acc: 0.6100
Epoch 22/70
1/1 [==============================] - 0s 171ms/step - loss: 0.7072 - acc: 0.4984 - val_loss: 0.6826 - val_acc: 0.3900
Epoch 23/70
1/1 [==============================] - 0s 176ms/step - loss: 0.7016 - acc: 0.4820 - val_loss: 0.6814 - val_acc: 0.3900
Epoch 24/70
1/1 [==============================] - 0s 178ms/step - loss: 0.6951 - a

1/1 [==============================] - 0s 176ms/step - loss: 0.7196 - acc: 0.4280 - val_loss: 0.6429 - val_acc: 0.4012
Epoch 4/70
1/1 [==============================] - 0s 179ms/step - loss: 0.7126 - acc: 0.4743 - val_loss: 0.6457 - val_acc: 0.4012
Epoch 5/70
1/1 [==============================] - 0s 170ms/step - loss: 0.7223 - acc: 0.5010 - val_loss: 0.6481 - val_acc: 0.5988
Epoch 6/70
1/1 [==============================] - 0s 190ms/step - loss: 0.7131 - acc: 0.5243 - val_loss: 0.6496 - val_acc: 0.5988
Epoch 7/70
1/1 [==============================] - 0s 172ms/step - loss: 0.7145 - acc: 0.5243 - val_loss: 0.6497 - val_acc: 0.5988
Epoch 8/70
1/1 [==============================] - 0s 178ms/step - loss: 0.7197 - acc: 0.5232 - val_loss: 0.6489 - val_acc: 0.5988
Epoch 9/70
1/1 [==============================] - 0s 184ms/step - loss: 0.7202 - acc: 0.5157 - val_loss: 0.6476 - val_acc: 0.5988
Epoch 10/70
1/1 [==============================] - 0s 189ms/step - loss: 0.7112 - acc: 0.5125 - val_l

Epoch 66/70
1/1 [==============================] - 0s 181ms/step - loss: 0.7052 - acc: 0.4380 - val_loss: 0.6427 - val_acc: 0.4012
Epoch 67/70
1/1 [==============================] - 0s 171ms/step - loss: 0.7069 - acc: 0.4380 - val_loss: 0.6427 - val_acc: 0.4012
Epoch 68/70
1/1 [==============================] - 0s 167ms/step - loss: 0.7034 - acc: 0.4392 - val_loss: 0.6426 - val_acc: 0.4012
Epoch 69/70
1/1 [==============================] - 0s 201ms/step - loss: 0.7055 - acc: 0.4337 - val_loss: 0.6425 - val_acc: 0.4012
Epoch 70/70
1/1 [==============================] - 0s 170ms/step - loss: 0.7041 - acc: 0.4265 - val_loss: 0.6425 - val_acc: 0.4012
sample weight :  [1.50370248e-04 5.39519851e-05 3.77626008e-05 ... 4.31807863e-05
 3.67490996e-05 5.41978420e-05]
x sum 1644947.0
Epoch 1/70
1/1 [==============================] - 6s 6s/step - loss: 0.9598 - acc: 0.3863 - val_loss: 0.9036 - val_acc: 0.3934
Epoch 2/70
1/1 [==============================] - 0s 208ms/step - loss: 0.9177 - acc: 0.

1/1 [==============================] - 0s 180ms/step - loss: 0.6835 - acc: 0.4927 - val_loss: 0.7312 - val_acc: 0.3934
Epoch 53/70
1/1 [==============================] - 0s 176ms/step - loss: 0.6798 - acc: 0.4935 - val_loss: 0.7313 - val_acc: 0.3934
Epoch 54/70
1/1 [==============================] - 0s 184ms/step - loss: 0.6890 - acc: 0.4826 - val_loss: 0.7316 - val_acc: 0.3934
Epoch 55/70
1/1 [==============================] - 0s 185ms/step - loss: 0.6853 - acc: 0.4984 - val_loss: 0.7318 - val_acc: 0.3934
Epoch 56/70
1/1 [==============================] - 0s 175ms/step - loss: 0.6834 - acc: 0.5131 - val_loss: 0.7321 - val_acc: 0.5936
Epoch 57/70
1/1 [==============================] - 0s 184ms/step - loss: 0.6786 - acc: 0.5033 - val_loss: 0.7323 - val_acc: 0.6066
Epoch 58/70
1/1 [==============================] - 0s 189ms/step - loss: 0.6868 - acc: 0.5102 - val_loss: 0.7326 - val_acc: 0.6066
Epoch 59/70
1/1 [==============================] - 0s 164ms/step - loss: 0.6818 - acc: 0.5128 -

Epoch 39/70
1/1 [==============================] - 0s 190ms/step - loss: 0.6791 - acc: 0.4533 - val_loss: 0.7294 - val_acc: 0.3822
Epoch 40/70
1/1 [==============================] - 0s 180ms/step - loss: 0.6828 - acc: 0.4544 - val_loss: 0.7294 - val_acc: 0.3822
Epoch 41/70
1/1 [==============================] - 0s 183ms/step - loss: 0.6818 - acc: 0.4429 - val_loss: 0.7295 - val_acc: 0.3822
Epoch 42/70
1/1 [==============================] - 0s 167ms/step - loss: 0.6822 - acc: 0.4369 - val_loss: 0.7295 - val_acc: 0.3822
Epoch 43/70
1/1 [==============================] - 0s 177ms/step - loss: 0.6790 - acc: 0.4521 - val_loss: 0.7295 - val_acc: 0.3822
Epoch 44/70
1/1 [==============================] - 0s 191ms/step - loss: 0.6769 - acc: 0.4403 - val_loss: 0.7295 - val_acc: 0.3822
Epoch 45/70
1/1 [==============================] - 0s 170ms/step - loss: 0.6761 - acc: 0.4498 - val_loss: 0.7295 - val_acc: 0.3822
Epoch 46/70
1/1 [==============================] - 0s 177ms/step - loss: 0.6819 - a

1/1 [==============================] - 0s 158ms/step - loss: 0.6952 - acc: 0.5278 - val_loss: 0.6960 - val_acc: 0.6264
Epoch 26/70
1/1 [==============================] - 0s 192ms/step - loss: 0.6964 - acc: 0.5177 - val_loss: 0.6960 - val_acc: 0.6264
Epoch 27/70
1/1 [==============================] - 0s 186ms/step - loss: 0.6953 - acc: 0.5186 - val_loss: 0.6960 - val_acc: 0.6264
Epoch 28/70
1/1 [==============================] - 0s 180ms/step - loss: 0.6954 - acc: 0.5027 - val_loss: 0.6959 - val_acc: 0.6264
Epoch 29/70
1/1 [==============================] - 0s 190ms/step - loss: 0.7014 - acc: 0.4958 - val_loss: 0.6959 - val_acc: 0.6264
Epoch 30/70
1/1 [==============================] - 0s 185ms/step - loss: 0.6969 - acc: 0.4812 - val_loss: 0.6959 - val_acc: 0.6264
Epoch 31/70
1/1 [==============================] - 0s 177ms/step - loss: 0.6966 - acc: 0.5045 - val_loss: 0.6959 - val_acc: 0.3253
Epoch 32/70
1/1 [==============================] - 0s 167ms/step - loss: 0.6956 - acc: 0.5085 -

Epoch 12/70
1/1 [==============================] - 0s 144ms/step - loss: 0.6926 - acc: 0.4461 - val_loss: 0.7118 - val_acc: 0.3762
Epoch 13/70
1/1 [==============================] - 0s 178ms/step - loss: 0.6902 - acc: 0.4659 - val_loss: 0.7111 - val_acc: 0.3762
Epoch 14/70
1/1 [==============================] - 0s 171ms/step - loss: 0.6903 - acc: 0.4757 - val_loss: 0.7106 - val_acc: 0.3762
Epoch 15/70
1/1 [==============================] - 0s 184ms/step - loss: 0.6921 - acc: 0.5010 - val_loss: 0.7102 - val_acc: 0.3762
Epoch 16/70
1/1 [==============================] - 0s 178ms/step - loss: 0.6946 - acc: 0.4953 - val_loss: 0.7100 - val_acc: 0.6238
Epoch 17/70
1/1 [==============================] - 0s 183ms/step - loss: 0.6932 - acc: 0.4981 - val_loss: 0.7098 - val_acc: 0.6238
Epoch 18/70
1/1 [==============================] - 0s 183ms/step - loss: 0.6867 - acc: 0.5099 - val_loss: 0.7098 - val_acc: 0.6238
Epoch 19/70
1/1 [==============================] - 0s 178ms/step - loss: 0.6921 - a

Epoch 1/70
1/1 [==============================] - 5s 5s/step - loss: 0.7135 - acc: 0.5870 - val_loss: 0.6995 - val_acc: 0.6428
Epoch 2/70
1/1 [==============================] - 0s 190ms/step - loss: 0.7076 - acc: 0.5660 - val_loss: 0.6979 - val_acc: 0.6428
Epoch 3/70
1/1 [==============================] - 0s 175ms/step - loss: 0.6956 - acc: 0.5418 - val_loss: 0.6986 - val_acc: 0.6428
Epoch 4/70
1/1 [==============================] - 0s 175ms/step - loss: 0.7026 - acc: 0.5105 - val_loss: 0.7008 - val_acc: 0.3572
Epoch 5/70
1/1 [==============================] - 0s 176ms/step - loss: 0.7020 - acc: 0.4745 - val_loss: 0.7033 - val_acc: 0.3572
Epoch 6/70
1/1 [==============================] - 0s 160ms/step - loss: 0.7062 - acc: 0.4642 - val_loss: 0.7049 - val_acc: 0.3572
Epoch 7/70
1/1 [==============================] - 0s 179ms/step - loss: 0.7025 - acc: 0.4524 - val_loss: 0.7053 - val_acc: 0.3572
Epoch 8/70
1/1 [==============================] - 0s 182ms/step - loss: 0.7068 - acc: 0.4561 

1/1 [==============================] - 0s 180ms/step - loss: 0.6942 - acc: 0.5042 - val_loss: 0.6986 - val_acc: 0.6031
Epoch 63/70
1/1 [==============================] - 0s 175ms/step - loss: 0.6880 - acc: 0.5142 - val_loss: 0.6987 - val_acc: 0.4236
Epoch 64/70
1/1 [==============================] - 0s 180ms/step - loss: 0.6961 - acc: 0.4938 - val_loss: 0.6988 - val_acc: 0.3443
Epoch 65/70
1/1 [==============================] - 0s 177ms/step - loss: 0.6886 - acc: 0.5088 - val_loss: 0.6988 - val_acc: 0.3417
Epoch 66/70
1/1 [==============================] - 0s 175ms/step - loss: 0.6938 - acc: 0.4984 - val_loss: 0.6989 - val_acc: 0.3538
Epoch 67/70
1/1 [==============================] - 0s 156ms/step - loss: 0.6926 - acc: 0.4984 - val_loss: 0.6989 - val_acc: 0.3572
Epoch 68/70
1/1 [==============================] - 0s 164ms/step - loss: 0.6953 - acc: 0.4826 - val_loss: 0.6989 - val_acc: 0.3572
Epoch 69/70
1/1 [==============================] - 0s 183ms/step - loss: 0.6918 - acc: 0.4806 -

Epoch 49/70
1/1 [==============================] - 0s 191ms/step - loss: 0.6973 - acc: 0.5102 - val_loss: 0.6828 - val_acc: 0.6005
Epoch 50/70
1/1 [==============================] - 0s 187ms/step - loss: 0.7006 - acc: 0.4987 - val_loss: 0.6828 - val_acc: 0.6005
Epoch 51/70
1/1 [==============================] - 0s 173ms/step - loss: 0.6959 - acc: 0.5116 - val_loss: 0.6827 - val_acc: 0.6005
Epoch 52/70
1/1 [==============================] - 0s 179ms/step - loss: 0.6981 - acc: 0.5093 - val_loss: 0.6826 - val_acc: 0.6005
Epoch 53/70
1/1 [==============================] - 0s 188ms/step - loss: 0.7004 - acc: 0.5134 - val_loss: 0.6825 - val_acc: 0.6005
Epoch 54/70
1/1 [==============================] - 0s 189ms/step - loss: 0.6967 - acc: 0.5203 - val_loss: 0.6824 - val_acc: 0.6005
Epoch 55/70
1/1 [==============================] - 0s 159ms/step - loss: 0.6979 - acc: 0.5220 - val_loss: 0.6824 - val_acc: 0.6005
Epoch 56/70
1/1 [==============================] - 0s 176ms/step - loss: 0.7012 - a

1/1 [==============================] - 0s 194ms/step - loss: 0.6877 - acc: 0.5473 - val_loss: 0.7058 - val_acc: 0.6074
Epoch 36/70
1/1 [==============================] - 0s 184ms/step - loss: 0.6903 - acc: 0.5626 - val_loss: 0.7058 - val_acc: 0.6074
Epoch 37/70
1/1 [==============================] - 0s 179ms/step - loss: 0.6922 - acc: 0.5459 - val_loss: 0.7058 - val_acc: 0.6074
Epoch 38/70
1/1 [==============================] - 0s 182ms/step - loss: 0.6884 - acc: 0.5387 - val_loss: 0.7058 - val_acc: 0.6074
Epoch 39/70
1/1 [==============================] - 0s 182ms/step - loss: 0.6908 - acc: 0.5444 - val_loss: 0.7058 - val_acc: 0.6074
Epoch 40/70
1/1 [==============================] - 0s 177ms/step - loss: 0.6901 - acc: 0.5416 - val_loss: 0.7058 - val_acc: 0.6074
Epoch 41/70
1/1 [==============================] - 0s 181ms/step - loss: 0.6887 - acc: 0.5551 - val_loss: 0.7058 - val_acc: 0.6074
Epoch 42/70
1/1 [==============================] - 0s 178ms/step - loss: 0.6889 - acc: 0.5456 -

Epoch 22/70
1/1 [==============================] - 0s 185ms/step - loss: 0.7123 - acc: 0.4518 - val_loss: 0.6483 - val_acc: 0.3822
Epoch 23/70
1/1 [==============================] - 0s 177ms/step - loss: 0.7117 - acc: 0.4423 - val_loss: 0.6486 - val_acc: 0.3822
Epoch 24/70
1/1 [==============================] - 0s 159ms/step - loss: 0.7110 - acc: 0.4400 - val_loss: 0.6486 - val_acc: 0.3822
Epoch 25/70
1/1 [==============================] - 0s 182ms/step - loss: 0.7102 - acc: 0.4323 - val_loss: 0.6484 - val_acc: 0.3822
Epoch 26/70
1/1 [==============================] - 0s 179ms/step - loss: 0.7109 - acc: 0.4426 - val_loss: 0.6481 - val_acc: 0.3822
Epoch 27/70
1/1 [==============================] - 0s 162ms/step - loss: 0.7139 - acc: 0.4271 - val_loss: 0.6478 - val_acc: 0.3822
Epoch 28/70
1/1 [==============================] - 0s 186ms/step - loss: 0.7108 - acc: 0.4487 - val_loss: 0.6475 - val_acc: 0.3822
Epoch 29/70
1/1 [==============================] - 0s 162ms/step - loss: 0.7146 - a

1/1 [==============================] - 0s 173ms/step - loss: 0.6934 - acc: 0.5186 - val_loss: 0.7000 - val_acc: 0.5979
Epoch 9/70
1/1 [==============================] - 0s 176ms/step - loss: 0.6894 - acc: 0.5499 - val_loss: 0.7000 - val_acc: 0.5979
Epoch 10/70
1/1 [==============================] - 0s 173ms/step - loss: 0.6935 - acc: 0.5614 - val_loss: 0.7002 - val_acc: 0.5979
Epoch 11/70
1/1 [==============================] - 0s 191ms/step - loss: 0.6934 - acc: 0.5718 - val_loss: 0.7003 - val_acc: 0.5979
Epoch 12/70
1/1 [==============================] - 0s 177ms/step - loss: 0.6926 - acc: 0.5631 - val_loss: 0.7004 - val_acc: 0.5979
Epoch 13/70
1/1 [==============================] - 0s 180ms/step - loss: 0.6978 - acc: 0.5623 - val_loss: 0.7004 - val_acc: 0.5979
Epoch 14/70
1/1 [==============================] - 0s 175ms/step - loss: 0.6866 - acc: 0.5804 - val_loss: 0.7002 - val_acc: 0.5979
Epoch 15/70
1/1 [==============================] - 0s 184ms/step - loss: 0.6887 - acc: 0.5686 - 

1/1 [==============================] - 0s 186ms/step - loss: 0.6907 - acc: 0.5812 - val_loss: 0.6997 - val_acc: 0.5979
sample weight :  [1.71472822e-04 6.18093235e-05 4.36359989e-05 ... 5.10491839e-05
 4.59696030e-05 5.08664085e-05]
x sum 1644947.0
Epoch 1/70
1/1 [==============================] - 5s 5s/step - loss: 0.7058 - acc: 0.4495 - val_loss: 0.6898 - val_acc: 0.3900
Epoch 2/70
1/1 [==============================] - 0s 188ms/step - loss: 0.7094 - acc: 0.4978 - val_loss: 0.6899 - val_acc: 0.3900
Epoch 3/70
1/1 [==============================] - 0s 175ms/step - loss: 0.7016 - acc: 0.4915 - val_loss: 0.6904 - val_acc: 0.6100
Epoch 4/70
1/1 [==============================] - 0s 180ms/step - loss: 0.6990 - acc: 0.5131 - val_loss: 0.6905 - val_acc: 0.6100
Epoch 5/70
1/1 [==============================] - 0s 186ms/step - loss: 0.7037 - acc: 0.5099 - val_loss: 0.6904 - val_acc: 0.6100
Epoch 6/70
1/1 [==============================] - 0s 182ms/step - loss: 0.7060 - acc: 0.5053 - val_loss:

Epoch 57/70
1/1 [==============================] - 0s 186ms/step - loss: 0.6961 - acc: 0.4921 - val_loss: 0.6898 - val_acc: 0.3900
Epoch 58/70
1/1 [==============================] - 0s 191ms/step - loss: 0.6959 - acc: 0.4895 - val_loss: 0.6898 - val_acc: 0.3900
Epoch 59/70
1/1 [==============================] - 0s 182ms/step - loss: 0.6958 - acc: 0.4817 - val_loss: 0.6898 - val_acc: 0.3900
Epoch 60/70
1/1 [==============================] - 0s 172ms/step - loss: 0.6929 - acc: 0.4961 - val_loss: 0.6898 - val_acc: 0.3900
Epoch 61/70
1/1 [==============================] - 0s 194ms/step - loss: 0.6962 - acc: 0.4835 - val_loss: 0.6898 - val_acc: 0.3900
Epoch 62/70
1/1 [==============================] - 0s 179ms/step - loss: 0.6920 - acc: 0.4961 - val_loss: 0.6898 - val_acc: 0.3900
Epoch 63/70
1/1 [==============================] - 0s 189ms/step - loss: 0.6957 - acc: 0.4699 - val_loss: 0.6897 - val_acc: 0.3900
Epoch 64/70
1/1 [==============================] - 0s 186ms/step - loss: 0.6918 - a

1/1 [==============================] - 0s 177ms/step - loss: 0.7016 - acc: 0.4659 - val_loss: 0.6687 - val_acc: 0.3831
Epoch 44/70
1/1 [==============================] - 0s 177ms/step - loss: 0.6968 - acc: 0.4538 - val_loss: 0.6687 - val_acc: 0.3831
Epoch 45/70
1/1 [==============================] - 0s 180ms/step - loss: 0.7060 - acc: 0.4616 - val_loss: 0.6687 - val_acc: 0.3831
Epoch 46/70
1/1 [==============================] - 0s 187ms/step - loss: 0.7113 - acc: 0.4423 - val_loss: 0.6686 - val_acc: 0.3831
Epoch 47/70
1/1 [==============================] - 0s 186ms/step - loss: 0.6998 - acc: 0.4573 - val_loss: 0.6685 - val_acc: 0.3831
Epoch 48/70
1/1 [==============================] - 0s 173ms/step - loss: 0.7001 - acc: 0.4613 - val_loss: 0.6684 - val_acc: 0.3831
Epoch 49/70
1/1 [==============================] - 0s 185ms/step - loss: 0.7082 - acc: 0.4441 - val_loss: 0.6683 - val_acc: 0.3831
Epoch 50/70
1/1 [==============================] - 0s 177ms/step - loss: 0.7089 - acc: 0.4665 -

Epoch 30/70
1/1 [==============================] - 0s 181ms/step - loss: 0.6979 - acc: 0.5597 - val_loss: 0.7006 - val_acc: 0.6048
Epoch 31/70
1/1 [==============================] - 0s 186ms/step - loss: 0.6957 - acc: 0.5634 - val_loss: 0.7002 - val_acc: 0.6048
Epoch 32/70
1/1 [==============================] - 0s 182ms/step - loss: 0.6954 - acc: 0.5605 - val_loss: 0.6999 - val_acc: 0.6048
Epoch 33/70
1/1 [==============================] - 0s 179ms/step - loss: 0.6949 - acc: 0.5554 - val_loss: 0.6996 - val_acc: 0.6048
Epoch 34/70
1/1 [==============================] - 0s 184ms/step - loss: 0.6964 - acc: 0.5410 - val_loss: 0.6993 - val_acc: 0.6048
Epoch 35/70
1/1 [==============================] - 0s 165ms/step - loss: 0.6924 - acc: 0.5542 - val_loss: 0.6991 - val_acc: 0.6048
Epoch 36/70
1/1 [==============================] - 0s 181ms/step - loss: 0.6908 - acc: 0.5485 - val_loss: 0.6990 - val_acc: 0.6048
Epoch 37/70
1/1 [==============================] - 0s 183ms/step - loss: 0.6942 - a

1/1 [==============================] - 0s 180ms/step - loss: 0.6912 - acc: 0.4708 - val_loss: 0.7252 - val_acc: 0.4193
Epoch 17/70
1/1 [==============================] - 0s 177ms/step - loss: 0.6848 - acc: 0.4685 - val_loss: 0.7252 - val_acc: 0.4193
Epoch 18/70
1/1 [==============================] - 0s 183ms/step - loss: 0.6889 - acc: 0.4573 - val_loss: 0.7251 - val_acc: 0.4193
Epoch 19/70
1/1 [==============================] - 0s 177ms/step - loss: 0.6861 - acc: 0.4932 - val_loss: 0.7250 - val_acc: 0.4193
Epoch 20/70
1/1 [==============================] - 0s 168ms/step - loss: 0.6871 - acc: 0.4849 - val_loss: 0.7250 - val_acc: 0.4193
Epoch 21/70
1/1 [==============================] - 1s 775ms/step - loss: 0.6858 - acc: 0.4918 - val_loss: 0.7250 - val_acc: 0.4193
Epoch 22/70
1/1 [==============================] - 0s 298ms/step - loss: 0.6944 - acc: 0.5042 - val_loss: 0.7251 - val_acc: 0.5807
Epoch 23/70
1/1 [==============================] - 0s 177ms/step - loss: 0.6873 - acc: 0.4843 -

Epoch 3/70
1/1 [==============================] - 0s 181ms/step - loss: 0.6964 - acc: 0.4768 - val_loss: 0.6855 - val_acc: 0.6324
Epoch 4/70
1/1 [==============================] - 0s 185ms/step - loss: 0.7029 - acc: 0.5013 - val_loss: 0.6869 - val_acc: 0.6324
Epoch 5/70
1/1 [==============================] - 0s 181ms/step - loss: 0.6991 - acc: 0.5295 - val_loss: 0.6878 - val_acc: 0.6324
Epoch 6/70
1/1 [==============================] - 0s 179ms/step - loss: 0.6981 - acc: 0.5456 - val_loss: 0.6878 - val_acc: 0.6324
Epoch 7/70
1/1 [==============================] - 0s 185ms/step - loss: 0.7093 - acc: 0.5450 - val_loss: 0.6873 - val_acc: 0.6324
Epoch 8/70
1/1 [==============================] - 0s 189ms/step - loss: 0.7044 - acc: 0.5326 - val_loss: 0.6865 - val_acc: 0.6324
Epoch 9/70
1/1 [==============================] - 0s 186ms/step - loss: 0.7088 - acc: 0.5151 - val_loss: 0.6857 - val_acc: 0.6324
Epoch 10/70
1/1 [==============================] - 0s 168ms/step - loss: 0.7077 - acc: 0.5

1/1 [==============================] - 0s 181ms/step - loss: 0.6940 - acc: 0.5068 - val_loss: 0.6850 - val_acc: 0.5677
Epoch 66/70
1/1 [==============================] - 0s 186ms/step - loss: 0.6956 - acc: 0.5065 - val_loss: 0.6850 - val_acc: 0.5358
Epoch 67/70
1/1 [==============================] - 0s 156ms/step - loss: 0.6973 - acc: 0.4953 - val_loss: 0.6849 - val_acc: 0.4702
Epoch 68/70
1/1 [==============================] - 0s 164ms/step - loss: 0.6987 - acc: 0.5160 - val_loss: 0.6849 - val_acc: 0.3960
Epoch 69/70
1/1 [==============================] - 0s 188ms/step - loss: 0.6923 - acc: 0.5042 - val_loss: 0.6848 - val_acc: 0.3753
Epoch 70/70
1/1 [==============================] - 0s 177ms/step - loss: 0.6956 - acc: 0.4976 - val_loss: 0.6848 - val_acc: 0.3736
sample weight :  [1.77218476e-04 6.33034879e-05 4.78809451e-05 ... 5.23360747e-05
 4.87189177e-05 5.08926730e-05]
x sum 1644947.0
Epoch 1/70
1/1 [==============================] - 5s 5s/step - loss: 0.7613 - acc: 0.3857 - val_

Epoch 52/70
1/1 [==============================] - 0s 184ms/step - loss: 0.6956 - acc: 0.4961 - val_loss: 0.6795 - val_acc: 0.3891
Epoch 53/70
1/1 [==============================] - 0s 185ms/step - loss: 0.7003 - acc: 0.4958 - val_loss: 0.6795 - val_acc: 0.3891
Epoch 54/70
1/1 [==============================] - 0s 173ms/step - loss: 0.7034 - acc: 0.4783 - val_loss: 0.6796 - val_acc: 0.3891
Epoch 55/70
1/1 [==============================] - 0s 184ms/step - loss: 0.6986 - acc: 0.4794 - val_loss: 0.6796 - val_acc: 0.3891
Epoch 56/70
1/1 [==============================] - 0s 178ms/step - loss: 0.6975 - acc: 0.4838 - val_loss: 0.6797 - val_acc: 0.3891
Epoch 57/70
1/1 [==============================] - 0s 179ms/step - loss: 0.6976 - acc: 0.4780 - val_loss: 0.6797 - val_acc: 0.3891
Epoch 58/70
1/1 [==============================] - 0s 182ms/step - loss: 0.7007 - acc: 0.4636 - val_loss: 0.6798 - val_acc: 0.3891
Epoch 59/70
1/1 [==============================] - 1s 809ms/step - loss: 0.7046 - a

1/1 [==============================] - 0s 187ms/step - loss: 0.6886 - acc: 0.4930 - val_loss: 0.7090 - val_acc: 0.3710
Epoch 39/70
1/1 [==============================] - 0s 179ms/step - loss: 0.6865 - acc: 0.4924 - val_loss: 0.7089 - val_acc: 0.3719
Epoch 40/70
1/1 [==============================] - 0s 171ms/step - loss: 0.6925 - acc: 0.4886 - val_loss: 0.7089 - val_acc: 0.3658
Epoch 41/70
1/1 [==============================] - 0s 179ms/step - loss: 0.6887 - acc: 0.5065 - val_loss: 0.7088 - val_acc: 0.3960
Epoch 42/70
1/1 [==============================] - 0s 155ms/step - loss: 0.6911 - acc: 0.5010 - val_loss: 0.7088 - val_acc: 0.4228
Epoch 43/70
1/1 [==============================] - 0s 183ms/step - loss: 0.6913 - acc: 0.4927 - val_loss: 0.7087 - val_acc: 0.6195
Epoch 44/70
1/1 [==============================] - 0s 159ms/step - loss: 0.6892 - acc: 0.5010 - val_loss: 0.7085 - val_acc: 0.6290
Epoch 45/70
1/1 [==============================] - 0s 152ms/step - loss: 0.6915 - acc: 0.5047 -

Epoch 25/70
1/1 [==============================] - 0s 189ms/step - loss: 0.6830 - acc: 0.5781 - val_loss: 0.7334 - val_acc: 0.6066
Epoch 26/70
1/1 [==============================] - 0s 173ms/step - loss: 0.6807 - acc: 0.5792 - val_loss: 0.7321 - val_acc: 0.6066
Epoch 27/70
1/1 [==============================] - 0s 194ms/step - loss: 0.6868 - acc: 0.5720 - val_loss: 0.7310 - val_acc: 0.6066
Epoch 28/70
1/1 [==============================] - 0s 172ms/step - loss: 0.6840 - acc: 0.5519 - val_loss: 0.7301 - val_acc: 0.6066
Epoch 29/70
1/1 [==============================] - 0s 170ms/step - loss: 0.6798 - acc: 0.5536 - val_loss: 0.7294 - val_acc: 0.6066
Epoch 30/70
1/1 [==============================] - 0s 183ms/step - loss: 0.6831 - acc: 0.5424 - val_loss: 0.7289 - val_acc: 0.6066
Epoch 31/70
1/1 [==============================] - 0s 179ms/step - loss: 0.6810 - acc: 0.5326 - val_loss: 0.7286 - val_acc: 0.6066
Epoch 32/70
1/1 [==============================] - 0s 173ms/step - loss: 0.6837 - a

1/1 [==============================] - 0s 178ms/step - loss: 0.7023 - acc: 0.4047 - val_loss: 0.6936 - val_acc: 0.3805
Epoch 12/70
1/1 [==============================] - 0s 178ms/step - loss: 0.7015 - acc: 0.4248 - val_loss: 0.6925 - val_acc: 0.3805
Epoch 13/70
1/1 [==============================] - 0s 183ms/step - loss: 0.6993 - acc: 0.4475 - val_loss: 0.6938 - val_acc: 0.3805
Epoch 14/70
1/1 [==============================] - 0s 159ms/step - loss: 0.6994 - acc: 0.5019 - val_loss: 0.6967 - val_acc: 0.6195
Epoch 15/70
1/1 [==============================] - 0s 177ms/step - loss: 0.6946 - acc: 0.5381 - val_loss: 0.7002 - val_acc: 0.6195
Epoch 16/70
1/1 [==============================] - 0s 159ms/step - loss: 0.7038 - acc: 0.5430 - val_loss: 0.7032 - val_acc: 0.6195
Epoch 17/70
1/1 [==============================] - 0s 177ms/step - loss: 0.7075 - acc: 0.5605 - val_loss: 0.7053 - val_acc: 0.6195
Epoch 18/70
1/1 [==============================] - 0s 185ms/step - loss: 0.7127 - acc: 0.5611 -

Epoch 1/70
1/1 [==============================] - 5s 5s/step - loss: 0.7062 - acc: 0.4449 - val_loss: 0.6645 - val_acc: 0.3995
Epoch 2/70
1/1 [==============================] - 0s 188ms/step - loss: 0.7088 - acc: 0.4771 - val_loss: 0.6639 - val_acc: 0.6005
Epoch 3/70
1/1 [==============================] - 0s 165ms/step - loss: 0.7115 - acc: 0.4993 - val_loss: 0.6639 - val_acc: 0.6005
Epoch 4/70
1/1 [==============================] - 0s 156ms/step - loss: 0.7028 - acc: 0.5039 - val_loss: 0.6639 - val_acc: 0.6005
Epoch 5/70
1/1 [==============================] - 0s 177ms/step - loss: 0.7093 - acc: 0.5102 - val_loss: 0.6640 - val_acc: 0.3995
Epoch 6/70
1/1 [==============================] - 0s 145ms/step - loss: 0.7124 - acc: 0.4872 - val_loss: 0.6642 - val_acc: 0.3995
Epoch 7/70
1/1 [==============================] - 0s 155ms/step - loss: 0.7027 - acc: 0.4881 - val_loss: 0.6646 - val_acc: 0.3995
Epoch 8/70
1/1 [==============================] - 0s 183ms/step - loss: 0.7037 - acc: 0.4711 

1/1 [==============================] - 0s 180ms/step - loss: 0.7015 - acc: 0.4524 - val_loss: 0.6644 - val_acc: 0.3995
Epoch 62/70
1/1 [==============================] - 0s 182ms/step - loss: 0.7028 - acc: 0.4518 - val_loss: 0.6644 - val_acc: 0.3995
Epoch 63/70
1/1 [==============================] - 0s 164ms/step - loss: 0.7028 - acc: 0.4536 - val_loss: 0.6644 - val_acc: 0.3995
Epoch 64/70
1/1 [==============================] - 0s 177ms/step - loss: 0.7017 - acc: 0.4636 - val_loss: 0.6644 - val_acc: 0.3995
Epoch 65/70
1/1 [==============================] - 0s 173ms/step - loss: 0.7005 - acc: 0.4737 - val_loss: 0.6644 - val_acc: 0.3995
Epoch 66/70
1/1 [==============================] - 0s 186ms/step - loss: 0.7020 - acc: 0.4694 - val_loss: 0.6644 - val_acc: 0.3995
Epoch 67/70
1/1 [==============================] - 0s 174ms/step - loss: 0.7045 - acc: 0.4507 - val_loss: 0.6644 - val_acc: 0.3995
Epoch 68/70
1/1 [==============================] - 0s 171ms/step - loss: 0.7034 - acc: 0.4633 -

Epoch 48/70
1/1 [==============================] - 0s 178ms/step - loss: 0.6979 - acc: 0.5194 - val_loss: 0.6777 - val_acc: 0.3831
Epoch 49/70
1/1 [==============================] - 0s 189ms/step - loss: 0.7025 - acc: 0.4987 - val_loss: 0.6776 - val_acc: 0.3831
Epoch 50/70
1/1 [==============================] - 0s 158ms/step - loss: 0.7015 - acc: 0.4869 - val_loss: 0.6776 - val_acc: 0.3831
Epoch 51/70
1/1 [==============================] - 0s 164ms/step - loss: 0.7026 - acc: 0.4866 - val_loss: 0.6776 - val_acc: 0.3831
Epoch 52/70
1/1 [==============================] - 0s 172ms/step - loss: 0.6994 - acc: 0.5062 - val_loss: 0.6777 - val_acc: 0.3831
Epoch 53/70
1/1 [==============================] - 0s 173ms/step - loss: 0.6987 - acc: 0.4987 - val_loss: 0.6777 - val_acc: 0.3831
Epoch 54/70
1/1 [==============================] - 0s 177ms/step - loss: 0.7030 - acc: 0.4918 - val_loss: 0.6778 - val_acc: 0.3831
Epoch 55/70
1/1 [==============================] - 0s 187ms/step - loss: 0.6972 - a

1/1 [==============================] - 0s 178ms/step - loss: 0.6853 - acc: 0.5024 - val_loss: 0.7149 - val_acc: 0.6100
Epoch 35/70
1/1 [==============================] - 0s 174ms/step - loss: 0.6879 - acc: 0.5220 - val_loss: 0.7151 - val_acc: 0.6100
Epoch 36/70
1/1 [==============================] - 0s 177ms/step - loss: 0.6859 - acc: 0.5234 - val_loss: 0.7153 - val_acc: 0.6100
Epoch 37/70
1/1 [==============================] - 0s 179ms/step - loss: 0.6872 - acc: 0.5370 - val_loss: 0.7154 - val_acc: 0.6100
Epoch 38/70
1/1 [==============================] - 0s 179ms/step - loss: 0.6890 - acc: 0.5289 - val_loss: 0.7155 - val_acc: 0.6100
Epoch 39/70
1/1 [==============================] - 0s 172ms/step - loss: 0.6852 - acc: 0.5387 - val_loss: 0.7155 - val_acc: 0.6100
Epoch 40/70
1/1 [==============================] - 0s 187ms/step - loss: 0.6848 - acc: 0.5347 - val_loss: 0.7155 - val_acc: 0.6100
Epoch 41/70
1/1 [==============================] - 0s 189ms/step - loss: 0.6856 - acc: 0.5306 -

Epoch 21/70
1/1 [==============================] - 0s 187ms/step - loss: 0.6872 - acc: 0.4415 - val_loss: 0.7386 - val_acc: 0.3719
Epoch 22/70
1/1 [==============================] - 0s 177ms/step - loss: 0.6866 - acc: 0.4438 - val_loss: 0.7391 - val_acc: 0.3719
Epoch 23/70
1/1 [==============================] - 0s 178ms/step - loss: 0.6804 - acc: 0.4544 - val_loss: 0.7393 - val_acc: 0.3719
Epoch 24/70
1/1 [==============================] - 0s 184ms/step - loss: 0.6870 - acc: 0.4300 - val_loss: 0.7392 - val_acc: 0.3719
Epoch 25/70
1/1 [==============================] - 0s 183ms/step - loss: 0.6837 - acc: 0.4314 - val_loss: 0.7389 - val_acc: 0.3719
Epoch 26/70
1/1 [==============================] - 0s 169ms/step - loss: 0.6902 - acc: 0.4334 - val_loss: 0.7384 - val_acc: 0.3719
Epoch 27/70
1/1 [==============================] - 0s 181ms/step - loss: 0.6854 - acc: 0.4328 - val_loss: 0.7378 - val_acc: 0.3719
Epoch 28/70
1/1 [==============================] - 0s 176ms/step - loss: 0.6845 - a

1/1 [==============================] - 0s 172ms/step - loss: 0.7095 - acc: 0.5019 - val_loss: 0.6599 - val_acc: 0.6238
Epoch 8/70
1/1 [==============================] - 0s 195ms/step - loss: 0.7098 - acc: 0.5232 - val_loss: 0.6593 - val_acc: 0.6238
Epoch 9/70
1/1 [==============================] - 0s 180ms/step - loss: 0.7058 - acc: 0.5266 - val_loss: 0.6589 - val_acc: 0.6238
Epoch 10/70
1/1 [==============================] - 0s 171ms/step - loss: 0.7057 - acc: 0.5139 - val_loss: 0.6587 - val_acc: 0.6238
Epoch 11/70
1/1 [==============================] - 0s 178ms/step - loss: 0.7023 - acc: 0.5542 - val_loss: 0.6586 - val_acc: 0.6238
Epoch 12/70
1/1 [==============================] - 0s 185ms/step - loss: 0.7095 - acc: 0.5272 - val_loss: 0.6587 - val_acc: 0.6238
Epoch 13/70
1/1 [==============================] - 0s 178ms/step - loss: 0.7098 - acc: 0.5209 - val_loss: 0.6590 - val_acc: 0.6238
Epoch 14/70
1/1 [==============================] - 0s 180ms/step - loss: 0.7041 - acc: 0.5444 - v

1/1 [==============================] - 0s 173ms/step - loss: 0.6960 - acc: 0.5329 - val_loss: 0.6578 - val_acc: 0.6057
Epoch 70/70
1/1 [==============================] - 0s 179ms/step - loss: 0.6972 - acc: 0.5177 - val_loss: 0.6573 - val_acc: 0.5884
sample weight :  [1.72401457e-04 6.29913768e-05 5.31745842e-05 ... 5.65518822e-05
 5.48392160e-05 5.51061434e-05]
x sum 1644947.0
Epoch 1/70
1/1 [==============================] - 5s 5s/step - loss: 0.7301 - acc: 0.4026 - val_loss: 0.7688 - val_acc: 0.3658
Epoch 2/70
1/1 [==============================] - 0s 179ms/step - loss: 0.7176 - acc: 0.4058 - val_loss: 0.7538 - val_acc: 0.3658
Epoch 3/70
1/1 [==============================] - 0s 187ms/step - loss: 0.7127 - acc: 0.4118 - val_loss: 0.7415 - val_acc: 0.3658
Epoch 4/70
1/1 [==============================] - 0s 181ms/step - loss: 0.7004 - acc: 0.4340 - val_loss: 0.7319 - val_acc: 0.3658
Epoch 5/70
1/1 [==============================] - 0s 182ms/step - loss: 0.6916 - acc: 0.4587 - val_loss

Epoch 56/70
1/1 [==============================] - 0s 176ms/step - loss: 0.6861 - acc: 0.4886 - val_loss: 0.7221 - val_acc: 0.3658
Epoch 57/70
1/1 [==============================] - 0s 171ms/step - loss: 0.6852 - acc: 0.4993 - val_loss: 0.7221 - val_acc: 0.3658
Epoch 58/70
1/1 [==============================] - 0s 180ms/step - loss: 0.6902 - acc: 0.4884 - val_loss: 0.7221 - val_acc: 0.3658
Epoch 59/70
1/1 [==============================] - 0s 182ms/step - loss: 0.6930 - acc: 0.4789 - val_loss: 0.7221 - val_acc: 0.3658
Epoch 60/70
1/1 [==============================] - 0s 180ms/step - loss: 0.6861 - acc: 0.5010 - val_loss: 0.7220 - val_acc: 0.3658
Epoch 61/70
1/1 [==============================] - 0s 180ms/step - loss: 0.6898 - acc: 0.5010 - val_loss: 0.7219 - val_acc: 0.3658
Epoch 62/70
1/1 [==============================] - 0s 176ms/step - loss: 0.6856 - acc: 0.4944 - val_loss: 0.7218 - val_acc: 0.3658
Epoch 63/70
1/1 [==============================] - 0s 174ms/step - loss: 0.6875 - a

1/1 [==============================] - 0s 161ms/step - loss: 0.6918 - acc: 0.4855 - val_loss: 0.6968 - val_acc: 0.3986
Epoch 43/70
1/1 [==============================] - 0s 181ms/step - loss: 0.6969 - acc: 0.4809 - val_loss: 0.6968 - val_acc: 0.3986
Epoch 44/70
1/1 [==============================] - 0s 184ms/step - loss: 0.7003 - acc: 0.4771 - val_loss: 0.6967 - val_acc: 0.3986
Epoch 45/70
1/1 [==============================] - 0s 188ms/step - loss: 0.6986 - acc: 0.4855 - val_loss: 0.6967 - val_acc: 0.3986
Epoch 46/70
1/1 [==============================] - 0s 186ms/step - loss: 0.6945 - acc: 0.4976 - val_loss: 0.6966 - val_acc: 0.3986
Epoch 47/70
1/1 [==============================] - 0s 183ms/step - loss: 0.6951 - acc: 0.4863 - val_loss: 0.6966 - val_acc: 0.3986
Epoch 48/70
1/1 [==============================] - 0s 166ms/step - loss: 0.6977 - acc: 0.5001 - val_loss: 0.6965 - val_acc: 0.3986
Epoch 49/70
1/1 [==============================] - 0s 181ms/step - loss: 0.6938 - acc: 0.4932 -

Epoch 29/70
1/1 [==============================] - 0s 176ms/step - loss: 0.7010 - acc: 0.4754 - val_loss: 0.6826 - val_acc: 0.3762
Epoch 30/70
1/1 [==============================] - 0s 182ms/step - loss: 0.7076 - acc: 0.4676 - val_loss: 0.6822 - val_acc: 0.3762
Epoch 31/70
1/1 [==============================] - 0s 165ms/step - loss: 0.6961 - acc: 0.4846 - val_loss: 0.6817 - val_acc: 0.3762
Epoch 32/70
1/1 [==============================] - 0s 167ms/step - loss: 0.6997 - acc: 0.4814 - val_loss: 0.6812 - val_acc: 0.3762
Epoch 33/70
1/1 [==============================] - 0s 179ms/step - loss: 0.6986 - acc: 0.4866 - val_loss: 0.6807 - val_acc: 0.3762
Epoch 34/70
1/1 [==============================] - 0s 186ms/step - loss: 0.7008 - acc: 0.4892 - val_loss: 0.6803 - val_acc: 0.3762
Epoch 35/70
1/1 [==============================] - 0s 175ms/step - loss: 0.7037 - acc: 0.4909 - val_loss: 0.6799 - val_acc: 0.3762
Epoch 36/70
1/1 [==============================] - 0s 181ms/step - loss: 0.7015 - a

1/1 [==============================] - 0s 168ms/step - loss: 0.6734 - acc: 0.5186 - val_loss: 0.7511 - val_acc: 0.4003
Epoch 16/70
1/1 [==============================] - 0s 170ms/step - loss: 0.6815 - acc: 0.4955 - val_loss: 0.7514 - val_acc: 0.4003
Epoch 17/70
1/1 [==============================] - 0s 186ms/step - loss: 0.6854 - acc: 0.4858 - val_loss: 0.7517 - val_acc: 0.4003
Epoch 18/70
1/1 [==============================] - 0s 171ms/step - loss: 0.6813 - acc: 0.4886 - val_loss: 0.7518 - val_acc: 0.4003
Epoch 19/70
1/1 [==============================] - 0s 183ms/step - loss: 0.6749 - acc: 0.4892 - val_loss: 0.7518 - val_acc: 0.4003
Epoch 20/70
1/1 [==============================] - 0s 186ms/step - loss: 0.6775 - acc: 0.4817 - val_loss: 0.7517 - val_acc: 0.4003
Epoch 21/70
1/1 [==============================] - 0s 156ms/step - loss: 0.6813 - acc: 0.4846 - val_loss: 0.7515 - val_acc: 0.4003
Epoch 22/70
1/1 [==============================] - 0s 163ms/step - loss: 0.6745 - acc: 0.4990 -

1/1 [==============================] - 5s 5s/step - loss: 0.6917 - acc: 0.4225 - val_loss: 0.7846 - val_acc: 0.3745
Epoch 2/70
1/1 [==============================] - 0s 178ms/step - loss: 0.6807 - acc: 0.4386 - val_loss: 0.7801 - val_acc: 0.3745
Epoch 3/70
1/1 [==============================] - 0s 184ms/step - loss: 0.6750 - acc: 0.4766 - val_loss: 0.7784 - val_acc: 0.3745
Epoch 4/70
1/1 [==============================] - 0s 183ms/step - loss: 0.6734 - acc: 0.5024 - val_loss: 0.7788 - val_acc: 0.6255
Epoch 5/70
1/1 [==============================] - 0s 185ms/step - loss: 0.6731 - acc: 0.5309 - val_loss: 0.7802 - val_acc: 0.6255
Epoch 6/70
1/1 [==============================] - 0s 185ms/step - loss: 0.6761 - acc: 0.5312 - val_loss: 0.7813 - val_acc: 0.6255
Epoch 7/70
1/1 [==============================] - 0s 183ms/step - loss: 0.6685 - acc: 0.5686 - val_loss: 0.7814 - val_acc: 0.6255
Epoch 8/70
1/1 [==============================] - 0s 183ms/step - loss: 0.6743 - acc: 0.5706 - val_loss:

Epoch 64/70
1/1 [==============================] - 0s 187ms/step - loss: 0.6691 - acc: 0.5237 - val_loss: 0.7784 - val_acc: 0.6255
Epoch 65/70
1/1 [==============================] - 0s 185ms/step - loss: 0.6711 - acc: 0.5203 - val_loss: 0.7784 - val_acc: 0.6255
Epoch 66/70
1/1 [==============================] - 0s 174ms/step - loss: 0.6666 - acc: 0.5301 - val_loss: 0.7784 - val_acc: 0.6255
Epoch 67/70
1/1 [==============================] - 0s 180ms/step - loss: 0.6637 - acc: 0.5243 - val_loss: 0.7784 - val_acc: 0.6255
Epoch 68/70
1/1 [==============================] - 0s 172ms/step - loss: 0.6681 - acc: 0.5160 - val_loss: 0.7784 - val_acc: 0.6255
Epoch 69/70
1/1 [==============================] - 0s 169ms/step - loss: 0.6690 - acc: 0.5272 - val_loss: 0.7784 - val_acc: 0.6255
Epoch 70/70
1/1 [==============================] - 0s 179ms/step - loss: 0.6702 - acc: 0.5122 - val_loss: 0.7784 - val_acc: 0.6255
sample weight :  [1.76560287e-04 6.44077383e-05 5.28020817e-05 ... 5.54408172e-05
 

1/1 [==============================] - 0s 191ms/step - loss: 0.6872 - acc: 0.5787 - val_loss: 0.7175 - val_acc: 0.6074
Epoch 51/70
1/1 [==============================] - 0s 172ms/step - loss: 0.6882 - acc: 0.5626 - val_loss: 0.7177 - val_acc: 0.6074
Epoch 52/70
1/1 [==============================] - 0s 175ms/step - loss: 0.6890 - acc: 0.5899 - val_loss: 0.7179 - val_acc: 0.6074
Epoch 53/70
1/1 [==============================] - 0s 183ms/step - loss: 0.6861 - acc: 0.5841 - val_loss: 0.7179 - val_acc: 0.6074
Epoch 54/70
1/1 [==============================] - 0s 188ms/step - loss: 0.6871 - acc: 0.5858 - val_loss: 0.7178 - val_acc: 0.6074
Epoch 55/70
1/1 [==============================] - 0s 185ms/step - loss: 0.6890 - acc: 0.5818 - val_loss: 0.7177 - val_acc: 0.6074
Epoch 56/70
1/1 [==============================] - 0s 184ms/step - loss: 0.6854 - acc: 0.5882 - val_loss: 0.7175 - val_acc: 0.6074
Epoch 57/70
1/1 [==============================] - 0s 183ms/step - loss: 0.6868 - acc: 0.5916 -

Epoch 37/70
1/1 [==============================] - 0s 179ms/step - loss: 0.6866 - acc: 0.4136 - val_loss: 0.7158 - val_acc: 0.3676
Epoch 38/70
1/1 [==============================] - 0s 157ms/step - loss: 0.6874 - acc: 0.4150 - val_loss: 0.7159 - val_acc: 0.3676
Epoch 39/70
1/1 [==============================] - 0s 147ms/step - loss: 0.6815 - acc: 0.4173 - val_loss: 0.7159 - val_acc: 0.3676
Epoch 40/70
1/1 [==============================] - 0s 197ms/step - loss: 0.6819 - acc: 0.4167 - val_loss: 0.7159 - val_acc: 0.3676
Epoch 41/70
1/1 [==============================] - 0s 194ms/step - loss: 0.6793 - acc: 0.4216 - val_loss: 0.7160 - val_acc: 0.3676
Epoch 42/70
1/1 [==============================] - 0s 168ms/step - loss: 0.6842 - acc: 0.4182 - val_loss: 0.7161 - val_acc: 0.3676
Epoch 43/70
1/1 [==============================] - 0s 178ms/step - loss: 0.6843 - acc: 0.4300 - val_loss: 0.7162 - val_acc: 0.3676
Epoch 44/70
1/1 [==============================] - 0s 180ms/step - loss: 0.6797 - a

1/1 [==============================] - 0s 176ms/step - loss: 0.6985 - acc: 0.4953 - val_loss: 0.6878 - val_acc: 0.6299
Epoch 24/70
1/1 [==============================] - 0s 185ms/step - loss: 0.6963 - acc: 0.4996 - val_loss: 0.6870 - val_acc: 0.6299
Epoch 25/70
1/1 [==============================] - 0s 171ms/step - loss: 0.6982 - acc: 0.5266 - val_loss: 0.6863 - val_acc: 0.6299
Epoch 26/70
1/1 [==============================] - 0s 185ms/step - loss: 0.6940 - acc: 0.5329 - val_loss: 0.6855 - val_acc: 0.6299
Epoch 27/70
1/1 [==============================] - 0s 178ms/step - loss: 0.6937 - acc: 0.5237 - val_loss: 0.6848 - val_acc: 0.6299
Epoch 28/70
1/1 [==============================] - 0s 178ms/step - loss: 0.7009 - acc: 0.5240 - val_loss: 0.6842 - val_acc: 0.6299
Epoch 29/70
1/1 [==============================] - 0s 190ms/step - loss: 0.7028 - acc: 0.5309 - val_loss: 0.6837 - val_acc: 0.6299
Epoch 30/70
1/1 [==============================] - 0s 179ms/step - loss: 0.6967 - acc: 0.5510 -

Epoch 10/70
1/1 [==============================] - 0s 179ms/step - loss: 0.6943 - acc: 0.4803 - val_loss: 0.6866 - val_acc: 0.3848
Epoch 11/70
1/1 [==============================] - 0s 188ms/step - loss: 0.7033 - acc: 0.4573 - val_loss: 0.6865 - val_acc: 0.3848
Epoch 12/70
1/1 [==============================] - 0s 175ms/step - loss: 0.7030 - acc: 0.4570 - val_loss: 0.6864 - val_acc: 0.3848
Epoch 13/70
1/1 [==============================] - 0s 177ms/step - loss: 0.7000 - acc: 0.4688 - val_loss: 0.6862 - val_acc: 0.3848
Epoch 14/70
1/1 [==============================] - 0s 181ms/step - loss: 0.6978 - acc: 0.4849 - val_loss: 0.6860 - val_acc: 0.3848
Epoch 15/70
1/1 [==============================] - 0s 181ms/step - loss: 0.6989 - acc: 0.4786 - val_loss: 0.6859 - val_acc: 0.3848
Epoch 16/70
1/1 [==============================] - 0s 189ms/step - loss: 0.6958 - acc: 0.4838 - val_loss: 0.6859 - val_acc: 0.3848
Epoch 17/70
1/1 [==============================] - 0s 189ms/step - loss: 0.6977 - a

Epoch 1/70
1/1 [==============================] - 5s 5s/step - loss: 0.6994 - acc: 0.5352 - val_loss: 0.6868 - val_acc: 0.6100
Epoch 2/70
1/1 [==============================] - 0s 175ms/step - loss: 0.6964 - acc: 0.5191 - val_loss: 0.6873 - val_acc: 0.3900
Epoch 3/70
1/1 [==============================] - 0s 177ms/step - loss: 0.7017 - acc: 0.4866 - val_loss: 0.6871 - val_acc: 0.3900
Epoch 4/70
1/1 [==============================] - 0s 177ms/step - loss: 0.6993 - acc: 0.4881 - val_loss: 0.6868 - val_acc: 0.6100
Epoch 5/70
1/1 [==============================] - 0s 174ms/step - loss: 0.7058 - acc: 0.4990 - val_loss: 0.6866 - val_acc: 0.6100
Epoch 6/70
1/1 [==============================] - 0s 185ms/step - loss: 0.7049 - acc: 0.4967 - val_loss: 0.6865 - val_acc: 0.6100
Epoch 7/70
1/1 [==============================] - 0s 181ms/step - loss: 0.7015 - acc: 0.5165 - val_loss: 0.6865 - val_acc: 0.6100
Epoch 8/70
1/1 [==============================] - 0s 182ms/step - loss: 0.6993 - acc: 0.5145 

Epoch 60/70
1/1 [==============================] - 0s 189ms/step - loss: 0.6973 - acc: 0.5119 - val_loss: 0.6866 - val_acc: 0.6100
Epoch 61/70
1/1 [==============================] - 0s 184ms/step - loss: 0.6956 - acc: 0.5260 - val_loss: 0.6866 - val_acc: 0.6100
Epoch 62/70
1/1 [==============================] - 0s 203ms/step - loss: 0.6961 - acc: 0.5160 - val_loss: 0.6867 - val_acc: 0.6100
Epoch 63/70
1/1 [==============================] - 0s 163ms/step - loss: 0.6961 - acc: 0.5252 - val_loss: 0.6866 - val_acc: 0.6100
Epoch 64/70
1/1 [==============================] - 0s 182ms/step - loss: 0.6968 - acc: 0.5186 - val_loss: 0.6867 - val_acc: 0.6100
Epoch 65/70
1/1 [==============================] - 0s 175ms/step - loss: 0.6970 - acc: 0.5188 - val_loss: 0.6867 - val_acc: 0.6100
Epoch 66/70
1/1 [==============================] - 0s 169ms/step - loss: 0.6983 - acc: 0.5217 - val_loss: 0.6867 - val_acc: 0.6100
Epoch 67/70
1/1 [==============================] - 0s 169ms/step - loss: 0.6958 - a

1/1 [==============================] - 0s 184ms/step - loss: 0.6829 - acc: 0.5289 - val_loss: 0.7296 - val_acc: 0.5919
Epoch 47/70
1/1 [==============================] - 0s 180ms/step - loss: 0.6821 - acc: 0.5111 - val_loss: 0.7296 - val_acc: 0.5919
Epoch 48/70
1/1 [==============================] - 0s 185ms/step - loss: 0.6838 - acc: 0.5114 - val_loss: 0.7296 - val_acc: 0.5919
Epoch 49/70
1/1 [==============================] - 0s 184ms/step - loss: 0.6843 - acc: 0.5347 - val_loss: 0.7295 - val_acc: 0.5919
Epoch 50/70
1/1 [==============================] - 0s 187ms/step - loss: 0.6797 - acc: 0.5361 - val_loss: 0.7295 - val_acc: 0.5919
Epoch 51/70
1/1 [==============================] - 0s 186ms/step - loss: 0.6838 - acc: 0.5269 - val_loss: 0.7295 - val_acc: 0.5919
Epoch 52/70
1/1 [==============================] - 0s 170ms/step - loss: 0.6842 - acc: 0.5249 - val_loss: 0.7295 - val_acc: 0.5919
Epoch 53/70
1/1 [==============================] - 0s 187ms/step - loss: 0.6823 - acc: 0.5217 -

Epoch 33/70
1/1 [==============================] - 0s 179ms/step - loss: 0.7012 - acc: 0.4740 - val_loss: 0.6791 - val_acc: 0.3719
Epoch 34/70
1/1 [==============================] - 0s 179ms/step - loss: 0.7009 - acc: 0.4806 - val_loss: 0.6790 - val_acc: 0.3719
Epoch 35/70
1/1 [==============================] - 0s 177ms/step - loss: 0.7006 - acc: 0.4846 - val_loss: 0.6789 - val_acc: 0.3719
Epoch 36/70
1/1 [==============================] - 0s 159ms/step - loss: 0.6984 - acc: 0.4898 - val_loss: 0.6789 - val_acc: 0.3719
Epoch 37/70
1/1 [==============================] - 0s 185ms/step - loss: 0.7054 - acc: 0.4766 - val_loss: 0.6789 - val_acc: 0.3719
Epoch 38/70
1/1 [==============================] - 0s 182ms/step - loss: 0.6994 - acc: 0.4771 - val_loss: 0.6789 - val_acc: 0.3719
Epoch 39/70
1/1 [==============================] - 0s 179ms/step - loss: 0.7049 - acc: 0.4823 - val_loss: 0.6789 - val_acc: 0.3719
Epoch 40/70
1/1 [==============================] - 0s 184ms/step - loss: 0.7035 - a

1/1 [==============================] - 0s 178ms/step - loss: 0.7069 - acc: 0.5341 - val_loss: 0.6865 - val_acc: 0.6186
Epoch 20/70
1/1 [==============================] - 0s 175ms/step - loss: 0.7045 - acc: 0.5551 - val_loss: 0.6876 - val_acc: 0.6186
Epoch 21/70
1/1 [==============================] - 0s 172ms/step - loss: 0.7067 - acc: 0.5479 - val_loss: 0.6885 - val_acc: 0.6186
Epoch 22/70
1/1 [==============================] - 0s 176ms/step - loss: 0.7077 - acc: 0.5490 - val_loss: 0.6892 - val_acc: 0.6186
Epoch 23/70
1/1 [==============================] - 0s 176ms/step - loss: 0.7066 - acc: 0.5689 - val_loss: 0.6896 - val_acc: 0.6186
Epoch 24/70
1/1 [==============================] - 0s 179ms/step - loss: 0.7043 - acc: 0.5743 - val_loss: 0.6897 - val_acc: 0.6186
Epoch 25/70
1/1 [==============================] - 0s 183ms/step - loss: 0.7111 - acc: 0.5634 - val_loss: 0.6895 - val_acc: 0.6186
Epoch 26/70
1/1 [==============================] - 0s 179ms/step - loss: 0.7000 - acc: 0.5718 -

Epoch 6/70
1/1 [==============================] - 0s 183ms/step - loss: 0.6924 - acc: 0.5493 - val_loss: 0.7208 - val_acc: 0.6204
Epoch 7/70
1/1 [==============================] - 0s 172ms/step - loss: 0.6832 - acc: 0.5344 - val_loss: 0.7228 - val_acc: 0.3796
Epoch 8/70
1/1 [==============================] - 0s 157ms/step - loss: 0.6953 - acc: 0.4927 - val_loss: 0.7256 - val_acc: 0.3796
Epoch 9/70
1/1 [==============================] - 0s 181ms/step - loss: 0.6881 - acc: 0.4832 - val_loss: 0.7285 - val_acc: 0.3796
Epoch 10/70
1/1 [==============================] - 0s 180ms/step - loss: 0.6945 - acc: 0.4397 - val_loss: 0.7306 - val_acc: 0.3796
Epoch 11/70
1/1 [==============================] - 0s 189ms/step - loss: 0.6943 - acc: 0.4285 - val_loss: 0.7316 - val_acc: 0.3796
Epoch 12/70
1/1 [==============================] - 0s 176ms/step - loss: 0.6892 - acc: 0.4360 - val_loss: 0.7315 - val_acc: 0.3796
Epoch 13/70
1/1 [==============================] - 0s 185ms/step - loss: 0.6958 - acc: 

1/1 [==============================] - 0s 184ms/step - loss: 0.6840 - acc: 0.5076 - val_loss: 0.7217 - val_acc: 0.6204
Epoch 69/70
1/1 [==============================] - 0s 170ms/step - loss: 0.6866 - acc: 0.5151 - val_loss: 0.7217 - val_acc: 0.6204
Epoch 70/70
1/1 [==============================] - 0s 171ms/step - loss: 0.6882 - acc: 0.5145 - val_loss: 0.7217 - val_acc: 0.6204
sample weight :  [1.76883584e-04 6.51888357e-05 5.39117047e-05 ... 5.58507189e-05
 5.54265540e-05 5.40301687e-05]
x sum 1644947.0
Epoch 1/70
1/1 [==============================] - 5s 5s/step - loss: 0.7430 - acc: 0.3940 - val_loss: 0.7391 - val_acc: 0.3822
Epoch 2/70
1/1 [==============================] - 0s 179ms/step - loss: 0.7323 - acc: 0.3940 - val_loss: 0.7259 - val_acc: 0.3822
Epoch 3/70
1/1 [==============================] - 0s 182ms/step - loss: 0.7251 - acc: 0.3966 - val_loss: 0.7151 - val_acc: 0.3822
Epoch 4/70
1/1 [==============================] - 0s 188ms/step - loss: 0.7125 - acc: 0.4118 - val_los

Epoch 55/70
1/1 [==============================] - 0s 166ms/step - loss: 0.6976 - acc: 0.4817 - val_loss: 0.6959 - val_acc: 0.3822
Epoch 56/70
1/1 [==============================] - 0s 172ms/step - loss: 0.6948 - acc: 0.4852 - val_loss: 0.6960 - val_acc: 0.3822
Epoch 57/70
1/1 [==============================] - 0s 166ms/step - loss: 0.7004 - acc: 0.4745 - val_loss: 0.6961 - val_acc: 0.3822
Epoch 58/70
1/1 [==============================] - 0s 165ms/step - loss: 0.6951 - acc: 0.4846 - val_loss: 0.6961 - val_acc: 0.3822
Epoch 59/70
1/1 [==============================] - 0s 170ms/step - loss: 0.6973 - acc: 0.4774 - val_loss: 0.6962 - val_acc: 0.3822
Epoch 60/70
1/1 [==============================] - 0s 144ms/step - loss: 0.6953 - acc: 0.4783 - val_loss: 0.6962 - val_acc: 0.3822
Epoch 61/70
1/1 [==============================] - 0s 176ms/step - loss: 0.6994 - acc: 0.4768 - val_loss: 0.6961 - val_acc: 0.3822
Epoch 62/70
1/1 [==============================] - 0s 173ms/step - loss: 0.6924 - a

1/1 [==============================] - 0s 179ms/step - loss: 0.6982 - acc: 0.5280 - val_loss: 0.6923 - val_acc: 0.6186
Epoch 42/70
1/1 [==============================] - 0s 185ms/step - loss: 0.6981 - acc: 0.5352 - val_loss: 0.6921 - val_acc: 0.6186
Epoch 43/70
1/1 [==============================] - 0s 181ms/step - loss: 0.6983 - acc: 0.5407 - val_loss: 0.6919 - val_acc: 0.6186
Epoch 44/70
1/1 [==============================] - 0s 180ms/step - loss: 0.6980 - acc: 0.5364 - val_loss: 0.6918 - val_acc: 0.6186
Epoch 45/70
1/1 [==============================] - 0s 184ms/step - loss: 0.6989 - acc: 0.5289 - val_loss: 0.6918 - val_acc: 0.6186
Epoch 46/70
1/1 [==============================] - 0s 170ms/step - loss: 0.6936 - acc: 0.5214 - val_loss: 0.6918 - val_acc: 0.6186
Epoch 47/70
1/1 [==============================] - 0s 185ms/step - loss: 0.6972 - acc: 0.5364 - val_loss: 0.6918 - val_acc: 0.6186
Epoch 48/70
1/1 [==============================] - 0s 184ms/step - loss: 0.6959 - acc: 0.5370 -

Epoch 28/70
1/1 [==============================] - 0s 186ms/step - loss: 0.6930 - acc: 0.4835 - val_loss: 0.7132 - val_acc: 0.3796
Epoch 29/70
1/1 [==============================] - 0s 182ms/step - loss: 0.6937 - acc: 0.4993 - val_loss: 0.7132 - val_acc: 0.3796
Epoch 30/70
1/1 [==============================] - 0s 177ms/step - loss: 0.6928 - acc: 0.4932 - val_loss: 0.7132 - val_acc: 0.3796
Epoch 31/70
1/1 [==============================] - 0s 175ms/step - loss: 0.6920 - acc: 0.4866 - val_loss: 0.7131 - val_acc: 0.3796
Epoch 32/70
1/1 [==============================] - 0s 155ms/step - loss: 0.6898 - acc: 0.4895 - val_loss: 0.7130 - val_acc: 0.3796
Epoch 33/70
1/1 [==============================] - 0s 180ms/step - loss: 0.6909 - acc: 0.4892 - val_loss: 0.7129 - val_acc: 0.3796
Epoch 34/70
1/1 [==============================] - 0s 178ms/step - loss: 0.6864 - acc: 0.4803 - val_loss: 0.7129 - val_acc: 0.3796
Epoch 35/70
1/1 [==============================] - 0s 180ms/step - loss: 0.6882 - a

1/1 [==============================] - 0s 182ms/step - loss: 0.7030 - acc: 0.5010 - val_loss: 0.6784 - val_acc: 0.3796
Epoch 15/70
1/1 [==============================] - 0s 157ms/step - loss: 0.7003 - acc: 0.5050 - val_loss: 0.6791 - val_acc: 0.3796
Epoch 16/70
1/1 [==============================] - 0s 163ms/step - loss: 0.7003 - acc: 0.5024 - val_loss: 0.6794 - val_acc: 0.3796
Epoch 17/70
1/1 [==============================] - 0s 194ms/step - loss: 0.7059 - acc: 0.4826 - val_loss: 0.6796 - val_acc: 0.3796
Epoch 18/70
1/1 [==============================] - 0s 184ms/step - loss: 0.7050 - acc: 0.4748 - val_loss: 0.6794 - val_acc: 0.3796
Epoch 19/70
1/1 [==============================] - 0s 187ms/step - loss: 0.7059 - acc: 0.4783 - val_loss: 0.6791 - val_acc: 0.3796
Epoch 20/70
1/1 [==============================] - 0s 190ms/step - loss: 0.7030 - acc: 0.5001 - val_loss: 0.6787 - val_acc: 0.3796
Epoch 21/70
1/1 [==============================] - 0s 187ms/step - loss: 0.7046 - acc: 0.4861 -

Epoch 1/70
1/1 [==============================] - 5s 5s/step - loss: 0.7616 - acc: 0.3914 - val_loss: 0.7451 - val_acc: 0.3900
Epoch 2/70
1/1 [==============================] - 0s 177ms/step - loss: 0.7438 - acc: 0.3911 - val_loss: 0.7293 - val_acc: 0.3900
Epoch 3/70
1/1 [==============================] - 0s 190ms/step - loss: 0.7309 - acc: 0.3934 - val_loss: 0.7158 - val_acc: 0.3900
Epoch 4/70
1/1 [==============================] - 0s 184ms/step - loss: 0.7198 - acc: 0.3989 - val_loss: 0.7046 - val_acc: 0.3900
Epoch 5/70
1/1 [==============================] - 0s 187ms/step - loss: 0.7132 - acc: 0.3986 - val_loss: 0.6958 - val_acc: 0.3900
Epoch 6/70
1/1 [==============================] - 0s 186ms/step - loss: 0.7150 - acc: 0.4176 - val_loss: 0.6892 - val_acc: 0.3900
Epoch 7/70
1/1 [==============================] - 0s 180ms/step - loss: 0.7039 - acc: 0.4481 - val_loss: 0.6849 - val_acc: 0.3900
Epoch 8/70
1/1 [==============================] - 0s 180ms/step - loss: 0.7022 - acc: 0.4754 

1/1 [==============================] - 0s 179ms/step - loss: 0.7025 - acc: 0.4490 - val_loss: 0.6852 - val_acc: 0.3900
Epoch 64/70
1/1 [==============================] - 0s 173ms/step - loss: 0.6950 - acc: 0.4674 - val_loss: 0.6851 - val_acc: 0.3900
Epoch 65/70
1/1 [==============================] - 0s 181ms/step - loss: 0.6987 - acc: 0.4659 - val_loss: 0.6851 - val_acc: 0.3900
Epoch 66/70
1/1 [==============================] - 0s 179ms/step - loss: 0.7067 - acc: 0.4567 - val_loss: 0.6850 - val_acc: 0.3900
Epoch 67/70
1/1 [==============================] - 0s 169ms/step - loss: 0.6963 - acc: 0.4711 - val_loss: 0.6849 - val_acc: 0.3900
Epoch 68/70
1/1 [==============================] - 0s 172ms/step - loss: 0.7000 - acc: 0.4625 - val_loss: 0.6848 - val_acc: 0.3900
Epoch 69/70
1/1 [==============================] - 0s 179ms/step - loss: 0.6975 - acc: 0.4720 - val_loss: 0.6847 - val_acc: 0.3900
Epoch 70/70
1/1 [==============================] - 0s 167ms/step - loss: 0.6968 - acc: 0.4817 -

Epoch 50/70
1/1 [==============================] - 0s 181ms/step - loss: 0.6879 - acc: 0.5372 - val_loss: 0.7140 - val_acc: 0.6057
Epoch 51/70
1/1 [==============================] - 0s 184ms/step - loss: 0.6864 - acc: 0.5485 - val_loss: 0.7140 - val_acc: 0.6057
Epoch 52/70
1/1 [==============================] - 0s 183ms/step - loss: 0.6867 - acc: 0.5510 - val_loss: 0.7142 - val_acc: 0.6057
Epoch 53/70
1/1 [==============================] - 0s 170ms/step - loss: 0.6872 - acc: 0.5280 - val_loss: 0.7143 - val_acc: 0.6057
Epoch 54/70
1/1 [==============================] - 0s 163ms/step - loss: 0.6845 - acc: 0.5473 - val_loss: 0.7143 - val_acc: 0.6057
Epoch 55/70
1/1 [==============================] - 0s 174ms/step - loss: 0.6862 - acc: 0.5430 - val_loss: 0.7142 - val_acc: 0.6057
Epoch 56/70
1/1 [==============================] - 0s 182ms/step - loss: 0.6852 - acc: 0.5413 - val_loss: 0.7142 - val_acc: 0.6057
Epoch 57/70
1/1 [==============================] - 0s 168ms/step - loss: 0.6835 - a

1/1 [==============================] - 0s 170ms/step - loss: 0.7092 - acc: 0.4484 - val_loss: 0.6736 - val_acc: 0.4047
Epoch 37/70
1/1 [==============================] - 0s 172ms/step - loss: 0.7022 - acc: 0.4547 - val_loss: 0.6739 - val_acc: 0.4047
Epoch 38/70
1/1 [==============================] - 0s 176ms/step - loss: 0.7022 - acc: 0.4492 - val_loss: 0.6741 - val_acc: 0.4047
Epoch 39/70
1/1 [==============================] - 0s 182ms/step - loss: 0.7064 - acc: 0.4366 - val_loss: 0.6740 - val_acc: 0.4047
Epoch 40/70
1/1 [==============================] - 0s 194ms/step - loss: 0.6986 - acc: 0.4547 - val_loss: 0.6739 - val_acc: 0.4047
Epoch 41/70
1/1 [==============================] - 0s 149ms/step - loss: 0.7049 - acc: 0.4550 - val_loss: 0.6737 - val_acc: 0.4047
Epoch 42/70
1/1 [==============================] - 0s 162ms/step - loss: 0.7044 - acc: 0.4530 - val_loss: 0.6734 - val_acc: 0.4047
Epoch 43/70
1/1 [==============================] - 0s 182ms/step - loss: 0.6999 - acc: 0.4605 -

Epoch 23/70
1/1 [==============================] - 0s 176ms/step - loss: 0.6847 - acc: 0.5631 - val_loss: 0.7238 - val_acc: 0.6091
Epoch 24/70
1/1 [==============================] - 0s 178ms/step - loss: 0.6879 - acc: 0.5410 - val_loss: 0.7243 - val_acc: 0.6091
Epoch 25/70
1/1 [==============================] - 0s 172ms/step - loss: 0.6827 - acc: 0.5649 - val_loss: 0.7249 - val_acc: 0.6091
Epoch 26/70
1/1 [==============================] - 0s 172ms/step - loss: 0.6889 - acc: 0.5660 - val_loss: 0.7256 - val_acc: 0.6091
Epoch 27/70
1/1 [==============================] - 0s 171ms/step - loss: 0.6854 - acc: 0.5689 - val_loss: 0.7264 - val_acc: 0.6091
Epoch 28/70
1/1 [==============================] - 0s 174ms/step - loss: 0.6809 - acc: 0.5660 - val_loss: 0.7273 - val_acc: 0.6091
Epoch 29/70
1/1 [==============================] - 0s 181ms/step - loss: 0.6841 - acc: 0.5847 - val_loss: 0.7281 - val_acc: 0.6091
Epoch 30/70
1/1 [==============================] - 0s 175ms/step - loss: 0.6799 - a

1/1 [==============================] - 0s 179ms/step - loss: 0.6922 - acc: 0.5306 - val_loss: 0.7135 - val_acc: 0.6109
Epoch 10/70
1/1 [==============================] - 0s 166ms/step - loss: 0.6887 - acc: 0.5444 - val_loss: 0.7120 - val_acc: 0.6109
Epoch 11/70
1/1 [==============================] - 0s 178ms/step - loss: 0.6992 - acc: 0.5076 - val_loss: 0.7104 - val_acc: 0.6109
Epoch 12/70
1/1 [==============================] - 0s 159ms/step - loss: 0.6976 - acc: 0.5007 - val_loss: 0.7087 - val_acc: 0.3891
Epoch 13/70
1/1 [==============================] - 0s 186ms/step - loss: 0.6907 - acc: 0.4981 - val_loss: 0.7074 - val_acc: 0.3891
Epoch 14/70
1/1 [==============================] - 0s 177ms/step - loss: 0.6911 - acc: 0.4852 - val_loss: 0.7062 - val_acc: 0.3891
Epoch 15/70
1/1 [==============================] - 0s 177ms/step - loss: 0.6977 - acc: 0.4656 - val_loss: 0.7054 - val_acc: 0.3891
Epoch 16/70
1/1 [==============================] - 0s 185ms/step - loss: 0.6921 - acc: 0.4478 -

Epoch 1/70
1/1 [==============================] - 5s 5s/step - loss: 0.7088 - acc: 0.5502 - val_loss: 0.6808 - val_acc: 0.5919
Epoch 2/70
1/1 [==============================] - 0s 149ms/step - loss: 0.7063 - acc: 0.5151 - val_loss: 0.6773 - val_acc: 0.4081
Epoch 3/70
1/1 [==============================] - 0s 187ms/step - loss: 0.7051 - acc: 0.4829 - val_loss: 0.6760 - val_acc: 0.4081
Epoch 4/70
1/1 [==============================] - 0s 193ms/step - loss: 0.7058 - acc: 0.4530 - val_loss: 0.6758 - val_acc: 0.4081
Epoch 5/70
1/1 [==============================] - 0s 180ms/step - loss: 0.7026 - acc: 0.4510 - val_loss: 0.6760 - val_acc: 0.4081
Epoch 6/70
1/1 [==============================] - 0s 184ms/step - loss: 0.7012 - acc: 0.4676 - val_loss: 0.6765 - val_acc: 0.4081
Epoch 7/70
1/1 [==============================] - 0s 171ms/step - loss: 0.7093 - acc: 0.4622 - val_loss: 0.6773 - val_acc: 0.4081
Epoch 8/70
1/1 [==============================] - 0s 171ms/step - loss: 0.7039 - acc: 0.4823 

1/1 [==============================] - 1s 888ms/step - loss: 0.6991 - acc: 0.4783 - val_loss: 0.6779 - val_acc: 0.4081
Epoch 59/70
1/1 [==============================] - 0s 172ms/step - loss: 0.7010 - acc: 0.4639 - val_loss: 0.6780 - val_acc: 0.4081
Epoch 60/70
1/1 [==============================] - 0s 150ms/step - loss: 0.6989 - acc: 0.4849 - val_loss: 0.6781 - val_acc: 0.4081
Epoch 61/70
1/1 [==============================] - 0s 179ms/step - loss: 0.7034 - acc: 0.4653 - val_loss: 0.6782 - val_acc: 0.4081
Epoch 62/70
1/1 [==============================] - 0s 175ms/step - loss: 0.7000 - acc: 0.4708 - val_loss: 0.6782 - val_acc: 0.4081
Epoch 63/70
1/1 [==============================] - 0s 185ms/step - loss: 0.6995 - acc: 0.4734 - val_loss: 0.6783 - val_acc: 0.4081
Epoch 64/70
1/1 [==============================] - 0s 178ms/step - loss: 0.7007 - acc: 0.4806 - val_loss: 0.6783 - val_acc: 0.4081
Epoch 65/70
1/1 [==============================] - 0s 175ms/step - loss: 0.7013 - acc: 0.4964 -

Epoch 45/70
1/1 [==============================] - 0s 176ms/step - loss: 0.6873 - acc: 0.4881 - val_loss: 0.7169 - val_acc: 0.3952
Epoch 46/70
1/1 [==============================] - 0s 188ms/step - loss: 0.6850 - acc: 0.4875 - val_loss: 0.7169 - val_acc: 0.3952
Epoch 47/70
1/1 [==============================] - 0s 179ms/step - loss: 0.6864 - acc: 0.4898 - val_loss: 0.7169 - val_acc: 0.3952
Epoch 48/70
1/1 [==============================] - 0s 180ms/step - loss: 0.6870 - acc: 0.4786 - val_loss: 0.7169 - val_acc: 0.3952
Epoch 49/70
1/1 [==============================] - 0s 191ms/step - loss: 0.6836 - acc: 0.4884 - val_loss: 0.7169 - val_acc: 0.3952
Epoch 50/70
1/1 [==============================] - 0s 181ms/step - loss: 0.6863 - acc: 0.4757 - val_loss: 0.7169 - val_acc: 0.3952
Epoch 51/70
1/1 [==============================] - 0s 192ms/step - loss: 0.6856 - acc: 0.4829 - val_loss: 0.7169 - val_acc: 0.3952
Epoch 52/70
1/1 [==============================] - 0s 180ms/step - loss: 0.6849 - a

1/1 [==============================] - 0s 165ms/step - loss: 0.7118 - acc: 0.5358 - val_loss: 0.6419 - val_acc: 0.6281
Epoch 32/70
1/1 [==============================] - 0s 182ms/step - loss: 0.7120 - acc: 0.5326 - val_loss: 0.6417 - val_acc: 0.6281
Epoch 33/70
1/1 [==============================] - 0s 192ms/step - loss: 0.7207 - acc: 0.5180 - val_loss: 0.6414 - val_acc: 0.6281
Epoch 34/70
1/1 [==============================] - 0s 184ms/step - loss: 0.7160 - acc: 0.5139 - val_loss: 0.6412 - val_acc: 0.6281
Epoch 35/70
1/1 [==============================] - 0s 194ms/step - loss: 0.7155 - acc: 0.5186 - val_loss: 0.6410 - val_acc: 0.6281
Epoch 36/70
1/1 [==============================] - 0s 173ms/step - loss: 0.7181 - acc: 0.5171 - val_loss: 0.6409 - val_acc: 0.6281
Epoch 37/70
1/1 [==============================] - 0s 181ms/step - loss: 0.7184 - acc: 0.5022 - val_loss: 0.6408 - val_acc: 0.6281
Epoch 38/70
1/1 [==============================] - 0s 184ms/step - loss: 0.7168 - acc: 0.5065 -

Epoch 18/70
1/1 [==============================] - 0s 192ms/step - loss: 0.7223 - acc: 0.4432 - val_loss: 0.6559 - val_acc: 0.3796
Epoch 19/70
1/1 [==============================] - 0s 169ms/step - loss: 0.7299 - acc: 0.4300 - val_loss: 0.6536 - val_acc: 0.3796
Epoch 20/70
1/1 [==============================] - 0s 174ms/step - loss: 0.7217 - acc: 0.4377 - val_loss: 0.6516 - val_acc: 0.3796
Epoch 21/70
1/1 [==============================] - 0s 187ms/step - loss: 0.7291 - acc: 0.4452 - val_loss: 0.6500 - val_acc: 0.3796
Epoch 22/70
1/1 [==============================] - 0s 182ms/step - loss: 0.7145 - acc: 0.4590 - val_loss: 0.6489 - val_acc: 0.3796
Epoch 23/70
1/1 [==============================] - 0s 193ms/step - loss: 0.7133 - acc: 0.4720 - val_loss: 0.6481 - val_acc: 0.3796
Epoch 24/70
1/1 [==============================] - 0s 168ms/step - loss: 0.7128 - acc: 0.4674 - val_loss: 0.6476 - val_acc: 0.3796
Epoch 25/70
1/1 [==============================] - 0s 179ms/step - loss: 0.7169 - a

1/1 [==============================] - 0s 179ms/step - loss: 0.6932 - acc: 0.4320 - val_loss: 0.7447 - val_acc: 0.3874
Epoch 5/70
1/1 [==============================] - 0s 172ms/step - loss: 0.6829 - acc: 0.4587 - val_loss: 0.7428 - val_acc: 0.3874
Epoch 6/70
1/1 [==============================] - 0s 187ms/step - loss: 0.6813 - acc: 0.4768 - val_loss: 0.7422 - val_acc: 0.6126
Epoch 7/70
1/1 [==============================] - 0s 178ms/step - loss: 0.6831 - acc: 0.5076 - val_loss: 0.7427 - val_acc: 0.6126
Epoch 8/70
1/1 [==============================] - 0s 171ms/step - loss: 0.6845 - acc: 0.5237 - val_loss: 0.7435 - val_acc: 0.6126
Epoch 9/70
1/1 [==============================] - 0s 192ms/step - loss: 0.6920 - acc: 0.5321 - val_loss: 0.7441 - val_acc: 0.6126
Epoch 10/70
1/1 [==============================] - 0s 153ms/step - loss: 0.6837 - acc: 0.5542 - val_loss: 0.7444 - val_acc: 0.6126
Epoch 11/70
1/1 [==============================] - 0s 161ms/step - loss: 0.6875 - acc: 0.5539 - val_

Epoch 67/70
1/1 [==============================] - 0s 179ms/step - loss: 0.6802 - acc: 0.4907 - val_loss: 0.7423 - val_acc: 0.3874
Epoch 68/70
1/1 [==============================] - 0s 182ms/step - loss: 0.6809 - acc: 0.4855 - val_loss: 0.7423 - val_acc: 0.3874
Epoch 69/70
1/1 [==============================] - 0s 183ms/step - loss: 0.6756 - acc: 0.4938 - val_loss: 0.7423 - val_acc: 0.3874
Epoch 70/70
1/1 [==============================] - 0s 179ms/step - loss: 0.6792 - acc: 0.4783 - val_loss: 0.7423 - val_acc: 0.3874
sample weight :  [1.78583226e-04 6.62426227e-05 5.83843908e-05 ... 5.77810736e-05
 5.90635099e-05 5.45246360e-05]
x sum 1644947.0
Epoch 1/70
1/1 [==============================] - 5s 5s/step - loss: 0.7172 - acc: 0.3995 - val_loss: 0.7152 - val_acc: 0.3822
Epoch 2/70
1/1 [==============================] - 0s 157ms/step - loss: 0.7058 - acc: 0.4070 - val_loss: 0.7090 - val_acc: 0.3822
Epoch 3/70
1/1 [==============================] - 0s 184ms/step - loss: 0.6972 - acc: 0.4

1/1 [==============================] - 0s 176ms/step - loss: 0.6941 - acc: 0.4881 - val_loss: 0.7032 - val_acc: 0.3822
Epoch 54/70
1/1 [==============================] - 0s 185ms/step - loss: 0.6935 - acc: 0.4829 - val_loss: 0.7031 - val_acc: 0.3822
Epoch 55/70
1/1 [==============================] - 0s 183ms/step - loss: 0.6973 - acc: 0.4889 - val_loss: 0.7031 - val_acc: 0.3822
Epoch 56/70
1/1 [==============================] - 0s 176ms/step - loss: 0.6932 - acc: 0.4771 - val_loss: 0.7031 - val_acc: 0.3822
Epoch 57/70
1/1 [==============================] - 0s 181ms/step - loss: 0.6933 - acc: 0.4921 - val_loss: 0.7030 - val_acc: 0.3822
Epoch 58/70
1/1 [==============================] - 0s 154ms/step - loss: 0.6898 - acc: 0.4838 - val_loss: 0.7030 - val_acc: 0.3822
Epoch 59/70
1/1 [==============================] - 0s 162ms/step - loss: 0.6887 - acc: 0.4996 - val_loss: 0.7030 - val_acc: 0.3822
Epoch 60/70
1/1 [==============================] - 0s 180ms/step - loss: 0.6938 - acc: 0.4909 -

Epoch 40/70
1/1 [==============================] - 0s 179ms/step - loss: 0.6759 - acc: 0.4967 - val_loss: 0.7599 - val_acc: 0.3840
Epoch 41/70
1/1 [==============================] - 0s 188ms/step - loss: 0.6724 - acc: 0.4987 - val_loss: 0.7602 - val_acc: 0.3840
Epoch 42/70
1/1 [==============================] - 0s 173ms/step - loss: 0.6723 - acc: 0.5007 - val_loss: 0.7606 - val_acc: 0.3840
Epoch 43/70
1/1 [==============================] - 0s 195ms/step - loss: 0.6735 - acc: 0.4958 - val_loss: 0.7609 - val_acc: 0.3840
Epoch 44/70
1/1 [==============================] - 0s 192ms/step - loss: 0.6720 - acc: 0.5007 - val_loss: 0.7611 - val_acc: 0.3840
Epoch 45/70
1/1 [==============================] - 0s 153ms/step - loss: 0.6739 - acc: 0.4771 - val_loss: 0.7614 - val_acc: 0.3840
Epoch 46/70
1/1 [==============================] - 0s 181ms/step - loss: 0.6747 - acc: 0.4930 - val_loss: 0.7614 - val_acc: 0.3840
Epoch 47/70
1/1 [==============================] - 0s 176ms/step - loss: 0.6729 - a

1/1 [==============================] - 0s 183ms/step - loss: 0.7118 - acc: 0.4820 - val_loss: 0.6568 - val_acc: 0.3917
Epoch 27/70
1/1 [==============================] - 0s 179ms/step - loss: 0.7120 - acc: 0.4846 - val_loss: 0.6570 - val_acc: 0.3917
Epoch 28/70
1/1 [==============================] - 0s 178ms/step - loss: 0.7127 - acc: 0.4803 - val_loss: 0.6570 - val_acc: 0.3917
Epoch 29/70
1/1 [==============================] - 0s 170ms/step - loss: 0.7115 - acc: 0.4840 - val_loss: 0.6570 - val_acc: 0.3917
Epoch 30/70
1/1 [==============================] - 0s 191ms/step - loss: 0.7110 - acc: 0.4628 - val_loss: 0.6567 - val_acc: 0.3917
Epoch 31/70
1/1 [==============================] - 0s 185ms/step - loss: 0.7152 - acc: 0.4697 - val_loss: 0.6564 - val_acc: 0.3917
Epoch 32/70
1/1 [==============================] - 0s 184ms/step - loss: 0.7082 - acc: 0.4970 - val_loss: 0.6561 - val_acc: 0.3917
Epoch 33/70
1/1 [==============================] - 0s 166ms/step - loss: 0.7155 - acc: 0.4789 -

Epoch 13/70
1/1 [==============================] - 0s 146ms/step - loss: 0.7038 - acc: 0.4245 - val_loss: 0.7000 - val_acc: 0.3917
Epoch 14/70
1/1 [==============================] - 0s 176ms/step - loss: 0.7014 - acc: 0.4357 - val_loss: 0.6982 - val_acc: 0.3917
Epoch 15/70
1/1 [==============================] - 0s 183ms/step - loss: 0.6966 - acc: 0.4513 - val_loss: 0.6964 - val_acc: 0.3917
Epoch 16/70
1/1 [==============================] - 0s 159ms/step - loss: 0.6957 - acc: 0.4533 - val_loss: 0.6949 - val_acc: 0.3917
Epoch 17/70
1/1 [==============================] - 0s 179ms/step - loss: 0.7007 - acc: 0.4478 - val_loss: 0.6935 - val_acc: 0.3917
Epoch 18/70
1/1 [==============================] - 0s 145ms/step - loss: 0.7013 - acc: 0.4665 - val_loss: 0.6924 - val_acc: 0.3917
Epoch 19/70
1/1 [==============================] - 0s 152ms/step - loss: 0.6929 - acc: 0.4705 - val_loss: 0.6915 - val_acc: 0.3917
Epoch 20/70
1/1 [==============================] - 0s 177ms/step - loss: 0.6942 - a

In [4]:
a = [i for i in boosted_classifier.staged_predict_proba(X_test)]
len(a[0])
a

[array([[0.2707135 , 0.7292865 ],
        [0.07444376, 0.92555624],
        [0.04450702, 0.955493  ],
        ...,
        [0.0898302 , 0.9101698 ],
        [0.11763357, 0.8823664 ],
        [0.23773056, 0.76226944]], dtype=float32),
 array([[0.40409738, 0.5959026 ],
        [0.24302235, 0.7569776 ],
        [0.19565073, 0.80434924],
        ...,
        [0.26112202, 0.73887795],
        [0.29030725, 0.7096927 ],
        [0.3814843 , 0.6185157 ]], dtype=float32),
 array([[0.4275194 , 0.5724806 ],
        [0.31221482, 0.6877852 ],
        [0.27394864, 0.72605133],
        ...,
        [0.32597783, 0.6740222 ],
        [0.34771815, 0.6522818 ],
        [0.4120743 , 0.5879257 ]], dtype=float32),
 array([[0.44819024, 0.5518098 ],
        [0.35904843, 0.64095163],
        [0.32766244, 0.6723376 ],
        ...,
        [0.36968783, 0.6303122 ],
        [0.386842  , 0.613158  ],
        [0.4362423 , 0.56375766]], dtype=float32),
 array([[0.45480263, 0.54519737],
        [0.3826213 , 0.6173788

In [5]:
aa = [i for i in boosted_classifier.staged_predict(X_test)]
aa

[array([1, 1, 1, ..., 1, 1, 1]),
 array([1, 1, 1, ..., 1, 1, 1]),
 array([1, 1, 1, ..., 1, 1, 1]),
 array([1, 1, 1, ..., 1, 1, 1]),
 array([1, 1, 1, ..., 1, 1, 1]),
 array([1, 1, 1, ..., 1, 1, 1]),
 array([1, 1, 1, ..., 1, 1, 1]),
 array([1, 1, 1, ..., 1, 1, 1]),
 array([1, 1, 1, ..., 1, 1, 1]),
 array([1, 1, 1, ..., 1, 1, 1]),
 array([1, 1, 1, ..., 1, 1, 1]),
 array([1, 1, 1, ..., 1, 1, 1]),
 array([1, 1, 1, ..., 1, 1, 1]),
 array([1, 1, 1, ..., 1, 1, 1]),
 array([1, 1, 1, ..., 1, 1, 1]),
 array([1, 1, 1, ..., 1, 1, 1]),
 array([1, 1, 1, ..., 1, 1, 1]),
 array([1, 1, 1, ..., 1, 1, 1]),
 array([1, 1, 1, ..., 1, 1, 1]),
 array([1, 1, 1, ..., 1, 1, 1]),
 array([1, 1, 1, ..., 1, 1, 1]),
 array([1, 1, 1, ..., 1, 1, 1]),
 array([1, 1, 1, ..., 1, 1, 1]),
 array([1, 1, 1, ..., 1, 1, 1]),
 array([1, 1, 1, ..., 1, 1, 1]),
 array([1, 1, 1, ..., 1, 1, 1]),
 array([1, 1, 1, ..., 1, 1, 1]),
 array([1, 1, 1, ..., 1, 1, 1]),
 array([1, 1, 1, ..., 1, 1, 1]),
 array([1, 1, 1, ..., 1, 1, 1]),
 array([1,

In [6]:
acc_list = [accuracy_score(y_test,i) for i in boosted_classifier.staged_predict(X_test)]
acc_list

[0.7637540453074434,
 0.7650485436893204,
 0.7624595469255664,
 0.7637540453074434,
 0.7637540453074434,
 0.7631067961165049,
 0.7631067961165049,
 0.7644012944983819,
 0.7637540453074434,
 0.7624595469255664,
 0.7572815533980582,
 0.7618122977346279,
 0.7618122977346279,
 0.7611650485436893,
 0.7585760517799353,
 0.7598705501618123,
 0.7637540453074434,
 0.7579288025889968,
 0.7618122977346279,
 0.7585760517799353,
 0.7585760517799353,
 0.7611650485436893,
 0.7592233009708738,
 0.7579288025889968,
 0.7592233009708738,
 0.7618122977346279,
 0.7592233009708738,
 0.7598705501618123,
 0.7579288025889968,
 0.7624595469255664,
 0.7579288025889968,
 0.7618122977346279,
 0.7579288025889968,
 0.7618122977346279,
 0.7585760517799353,
 0.7585760517799353,
 0.7592233009708738,
 0.7579288025889968,
 0.7631067961165049,
 0.7592233009708738,
 0.7579288025889968,
 0.7572815533980582,
 0.7572815533980582,
 0.7598705501618123,
 0.7598705501618123,
 0.7598705501618123,
 0.7611650485436893,
 0.7618122977

In [26]:
y_test

array([1, 0, 1, ..., 1, 1, 1])

In [ ]:
boosted_classifier.estimator_errors_

- .fit(new_x, new_y) : Adaboost accuracy : 0.7501618122977346, precision : 0.7742914979757085, recall : 0.8243534482758621, f1 : 0.7985386221294364, roc_auc : 0.7314635960990331
- .fit(new_x, new_y, **kwargs) : accuracy : 0.7430420711974111, precision : 0.7734294541709578, recall : 0.8092672413793104, f1 : 0.7909426013691417, roc_auc : 0.7263516109651819
- .fit(new_x, new_y, sample_weight=sample_weight) : 


In [5]:
y_pred_test = boosted_classifier.predict(X_test)

y_pred_test[y_pred_test>0.5]=1
y_pred_test[y_pred_test<=0.5]=0
precision = precision_score(y_test, y_pred_test)
recall = recall_score(y_test, y_pred_test)
f1 = f1_score(y_test, y_pred_test)
roc_auc = roc_auc_score(y_test, y_pred_test)
acc = accuracy_score(y_test, y_pred_test)

print(f'accuracy : {acc}, precision : {precision}, recall : {recall}, f1 : {f1}, roc_auc : {roc_auc}')

accuracy : 0.7430420711974111, precision : 0.7734294541709578, recall : 0.8092672413793104, f1 : 0.7909426013691417, roc_auc : 0.7263516109651819


## 모델저장

In [8]:
import pickle
import joblib

joblib.dump(boosted_classifier, './models/adaboost_lstm.pkl') 
reload_model = joblib.load('./models/adaboost_lstm.pkl') 

INFO:tensorflow:Assets written to: ram://4fc3a096-2c5e-42aa-8ed7-0d35dd718c6c/assets


INFO:tensorflow:Assets written to: ram://3f4d161d-ae84-45e1-b949-b9e25640463a/assets


INFO:tensorflow:Assets written to: ram://3f4d161d-ae84-45e1-b949-b9e25640463a/assets


INFO:tensorflow:Assets written to: ram://aea38500-abca-43c1-9f03-3d652beb35d0/assets


INFO:tensorflow:Assets written to: ram://aea38500-abca-43c1-9f03-3d652beb35d0/assets


INFO:tensorflow:Assets written to: ram://d8af8a47-726a-41d3-be0d-0593228ced6d/assets


INFO:tensorflow:Assets written to: ram://d8af8a47-726a-41d3-be0d-0593228ced6d/assets


INFO:tensorflow:Assets written to: ram://f103218e-4d08-43a8-b7ad-52bd21b3ac7f/assets


INFO:tensorflow:Assets written to: ram://f103218e-4d08-43a8-b7ad-52bd21b3ac7f/assets


INFO:tensorflow:Assets written to: ram://d990fedd-2b25-49b4-969d-be78df877613/assets


INFO:tensorflow:Assets written to: ram://d990fedd-2b25-49b4-969d-be78df877613/assets


INFO:tensorflow:Assets written to: ram://e6789a93-f575-469c-93b0-687ba122780c/assets


INFO:tensorflow:Assets written to: ram://e6789a93-f575-469c-93b0-687ba122780c/assets


INFO:tensorflow:Assets written to: ram://a414dbcf-accd-4e11-a6f7-61ffa027a2fe/assets


INFO:tensorflow:Assets written to: ram://a414dbcf-accd-4e11-a6f7-61ffa027a2fe/assets


INFO:tensorflow:Assets written to: ram://878dedc5-d1ab-447a-9325-76d09d8e4c61/assets


INFO:tensorflow:Assets written to: ram://878dedc5-d1ab-447a-9325-76d09d8e4c61/assets


INFO:tensorflow:Assets written to: ram://9d9a03cd-e0f8-48d3-83b3-5dc29a0c49b3/assets


INFO:tensorflow:Assets written to: ram://9d9a03cd-e0f8-48d3-83b3-5dc29a0c49b3/assets


INFO:tensorflow:Assets written to: ram://7f4b6df1-1710-4b94-b145-4df49eb2c1df/assets


INFO:tensorflow:Assets written to: ram://7f4b6df1-1710-4b94-b145-4df49eb2c1df/assets


INFO:tensorflow:Assets written to: ram://6882bb5a-c30f-45d5-a61f-6f5376d4b070/assets


INFO:tensorflow:Assets written to: ram://6882bb5a-c30f-45d5-a61f-6f5376d4b070/assets


INFO:tensorflow:Assets written to: ram://928e318e-066e-448b-b9e4-fa49130710d1/assets


INFO:tensorflow:Assets written to: ram://928e318e-066e-448b-b9e4-fa49130710d1/assets


INFO:tensorflow:Assets written to: ram://2dec7e68-30b3-412b-8dc2-4baace97d62b/assets


INFO:tensorflow:Assets written to: ram://2dec7e68-30b3-412b-8dc2-4baace97d62b/assets


INFO:tensorflow:Assets written to: ram://d6187611-ec92-4789-a080-27933b012dcc/assets


INFO:tensorflow:Assets written to: ram://d6187611-ec92-4789-a080-27933b012dcc/assets


INFO:tensorflow:Assets written to: ram://499bb4db-f428-4561-bc88-a98f49c11e17/assets


INFO:tensorflow:Assets written to: ram://499bb4db-f428-4561-bc88-a98f49c11e17/assets


INFO:tensorflow:Assets written to: ram://12e1fa1c-0401-497a-90da-48a9b4f0b715/assets


INFO:tensorflow:Assets written to: ram://12e1fa1c-0401-497a-90da-48a9b4f0b715/assets


INFO:tensorflow:Assets written to: ram://94288a7f-24f6-4f72-9a74-76d071b01a68/assets


INFO:tensorflow:Assets written to: ram://94288a7f-24f6-4f72-9a74-76d071b01a68/assets


INFO:tensorflow:Assets written to: ram://53037386-12b4-4385-b5cb-98f69aed3181/assets


INFO:tensorflow:Assets written to: ram://53037386-12b4-4385-b5cb-98f69aed3181/assets


INFO:tensorflow:Assets written to: ram://56c8a39b-d555-4124-a103-af0a24f06b89/assets


INFO:tensorflow:Assets written to: ram://56c8a39b-d555-4124-a103-af0a24f06b89/assets


## etc..

In [4]:
a = [i for i in boosted_classifier.staged_predict_proba(X_test)]
len(a[0])
a

[array([[0.14671701, 0.853283  ],
        [0.15134184, 0.84865814],
        [0.09548907, 0.9045109 ],
        ...,
        [0.12648392, 0.8735161 ],
        [0.10223823, 0.89776176],
        [0.23039924, 0.76960075]], dtype=float32),
 array([[0.8154902 , 0.18450987],
        [0.8216686 , 0.17833138],
        [0.0754172 , 0.9245828 ],
        ...,
        [0.20071441, 0.7992856 ],
        [0.06067883, 0.9393212 ],
        [0.0725329 , 0.9274671 ]], dtype=float32),
 array([[0.34155625, 0.6584438 ],
        [0.34451336, 0.6554866 ],
        [0.03459236, 0.9654076 ],
        ...,
        [0.08024294, 0.919757  ],
        [0.04676704, 0.95323294],
        [0.12316583, 0.8768342 ]], dtype=float32),
 array([[0.5092239 , 0.49077615],
        [0.60728794, 0.3927121 ],
        [0.16986866, 0.8301313 ],
        ...,
        [0.2854696 , 0.7145304 ],
        [0.20876725, 0.79123276],
        [0.24563938, 0.7543606 ]], dtype=float32),
 array([[0.53762466, 0.46237534],
        [0.3876752 , 0.6123248

In [8]:
[accuracy_score(y_test,i) for i in boosted_classifier.staged_predict(X_test)]

[0.7682847896440129,
 0.6220064724919094,
 0.7592233009708738,
 0.6517799352750809,
 0.7391585760517799,
 0.6660194174757281,
 0.7249190938511327,
 0.6724919093851133,
 0.7171521035598706,
 0.6964401294498382]

In [27]:
boosted_classifier.estimator_weights_

array([1., 1., 1., 1., 1.])

In [28]:
boosted_classifier.estimator_errors_

array([0.13636364, 0.18618371, 0.77088202, 0.80480714, 0.13529329])

In [100]:
y_pred_test

array([0, 0, 1, ..., 1, 1, 1])

In [101]:
boosted_classifier.estimators_

In [102]:
boosted_classifier.estimator_weights_

array([1., 1., 1., 1., 1.])

In [103]:
boosted_classifier.estimator_errors_

array([0.19136202, 0.19596451, 0.16152457, 0.14712343, 0.16450197])